### ISSUE TITLE
Usage stats tracking sets opt _in_ value to opt _out_ value

### ISSUE THREAD

**Issue by fiendish** [HL7/fhir-ig-publisher#100]
https://github.com/HL7/fhir-ig-publisher/blob/0599f3342903e805ac248cae5f0c255af3e2e102/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L1560-L1561

https://github.com/HL7/fhir-ig-publisher/blob/0599f3342903e805ac248cae5f0c255af3e2e102/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L1800

https://github.com/HL7/fhir-ig-publisher/blob/680e3142c3a1f8050ac4949bd7a06b6b07f6e820/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/ExtensionTracker.java#L230-L232

https://github.com/HL7/fhir-ig-publisher/blob/680e3142c3a1f8050ac4949bd7a06b6b07f6e820/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/ExtensionTracker.java#L265-L273

**Comment by grahamegrieve** [comment]
oops. Fixed
