### ISSUE TITLE
How to actually set the different build modes?

### ISSUE THREAD

**Issue by fiendish** [HL7/fhir-ig-publisher#101]
I see only
https://github.com/HL7/fhir-ig-publisher/blob/0599f3342903e805ac248cae5f0c255af3e2e102/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L7363-L7364
and
https://github.com/HL7/fhir-ig-publisher/blob/0599f3342903e805ac248cae5f0c255af3e2e102/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L7279-L7280

What about the rest of https://github.com/HL7/fhir-ig-publisher/blob/0599f3342903e805ac248cae5f0c255af3e2e102/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L466 ?

I don't see where those modes get set anywhere.

Also why hasParam vs hasNamedParam? Those functions both do the same thing.

https://github.com/HL7/fhir-ig-publisher/blob/0599f3342903e805ac248cae5f0c255af3e2e102/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L7034-L7039
https://github.com/HL7/fhir-ig-publisher/blob/0599f3342903e805ac248cae5f0c255af3e2e102/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L7053-L7060

**Comment by grahamegrieve** [comment]
Modes:
- manual is the default
- only a few of use publication
- webserver is not currently supported
- autobuild is set by the ci-build when it runs - adds some extra restrictions.

I removed hasParam()

**Comment by lmckenzi** [comment]
Questions answered.  Closing.  If further information is needed, please open a new issue.
