### ISSUE TITLE
If the usage stat reporting ignores the setting, then it's not really opt-in or opt-out.

### ISSUE THREAD

**Issue by fiendish** [HL7/fhir-ig-publisher#102]
https://github.com/HL7/fhir-ig-publisher/blob/0599f3342903e805ac248cae5f0c255af3e2e102/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L1795-L1798
https://github.com/HL7/fhir-ig-publisher/blob/0599f3342903e805ac248cae5f0c255af3e2e102/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L2192-L2195

Also, npmName.contains some tiny substring is an extremely unfair check.

**Comment by grahamegrieve** [comment]
Not sure what your point is here. Using the ci-build is opting into the statistics - there's no choice. That's a policy question. And HL7, argonaut, and IHE guides are also opted in by organizational arrangement.

**Comment by fiendish** [comment]
> And HL7, argonaut, and IHE guides are also opted in by organizational arrangement.

Maybe you meant startswith and not contains, then? Because it looks like if an npmName is "djeiejsiweihejsjeine" then you force it to transmit stats regardless of what the author has asked for.

**Comment by grahamegrieve** [comment]
> And can't those organizations arrange themselves to opt in/out by using the available opt in/out arguments?

I know the editors. So I opted in for them since I don't rely on them to actually get it right

> The publisher documentation

fair point. I'll clarify

**Comment by grahamegrieve** [comment]
Not that I can find where it's documented at all. You have a source?

**Comment by fiendish** [comment]
There's one buried under ig.ini on https://build.fhir.org/ig/FHIR/ig-guidance/branches/master/using-templates.html

**Comment by grahamegrieve** [comment]
thanks. I didn't think to look there. Fixed.

**Comment by fiendish** [comment]
Thanks. I do think that you should still change the .contains("foo") to .startsWith("foo.") though. (Not sure if you saw that update. I have a terrible habit of posting to github from my phone, screwing it up, and then editing after the comment is posted.)

**Comment by grahamegrieve** [comment]
I have changed it to contains 'ihe.' etc. Given the way package naming works, this should be right, and I documented as that
