### ISSUE TITLE
Errors in Differential View -- USCore and Plan-Net

### ISSUE THREAD

**Issue by saulakravitz** [HL7/fhir-ig-publisher#106]
The differential view does not appear to correctly highlight changes in cardinality.
Look at the PractitionerRole resource/profile in R4[http://hl7.org/fhir/R4/practitionerrole.html], USCore [http://hl7.org/fhir/us/core/STU3/StructureDefinition-us-core-practitionerrole.html], and Plan-Net [https://build.fhir.org/ig/HL7/davinci-pdex-plan-net/StructureDefinition-plannet-PractitionerRole.html]

Here is R4:
image.png
![image](https://user-images.githubusercontent.com/37216915/83778432-ba3b4200-a658-11ea-9466-b40e8e3094d5.png)

Here is USCore differential (partial): Note that cardinalities for specialty and code have changed, but are not highlighted as changed.
image.png
![image](https://user-images.githubusercontent.com/37216915/83778471-c3c4aa00-a658-11ea-9a83-bf52bc4bb4f5.png)

Here is the Differential view for part of Plan-Net PractitionerRole (based on R4). Same issue. Cardinalities have changed, but not highlighted.
image.png
![image](https://user-images.githubusercontent.com/37216915/83778497-cb844e80-a658-11ea-9170-e6fc1f211f5b.png)

**Comment by grahamegrieve** [comment]
It looks like I already fixed this

**Comment by lmckenzi** [comment]
No argument from submitter.  Presume fixed and closing
