### ISSUE TITLE
Snapshot generation with sparse differentials

### ISSUE THREAD

**Issue by ngfreiter** [HL7/fhir-ig-publisher#111]
@saulakravitz and I have come across an issue relating to his [carin-bb IG](https://github.com/saulakravitz/carin-bb/tree/saul), that to me looks like it might be related to the IG Publisher's handling of sparse differentials. When that IG is generated using SUSHI 0.13.2, the IG Publisher quits with the following error:
```
java.lang.Exception: Error generating snapshot for CARIN BB ExplanationOfBenefit Inpatient Facility(CARIN-BB-ExplanationOfBenefit-Inpatient-Facility): Unable to generate snapshot for http://hl7.org/fhir/us/carin-bb/StructureDefinition/CARIN-BB-ExplanationOfBenefit-Inpatient-Facility in C:\Users\nfreiter\dev\standardhealth\carin-bb\input\profiles\structuredefinition-CARIN-BB-ExplanationOfBenefit-Inpatient-Facility
        at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshots(Publisher.java:4224)
        at org.hl7.fhir.igtools.publisher.Publisher.loadConformance(Publisher.java:3605)
        at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:836)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:698)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:7533)
Caused by: org.hl7.fhir.exceptions.FHIRException: Unable to generate snapshot for http://hl7.org/fhir/us/carin-bb/StructureDefinition/CARIN-BB-ExplanationOfBenefit-Inpatient-Facility in C:\Users\nfreiter\dev\standardhealth\carin-bb\input\profiles\structuredefinition-CARIN-BB-ExplanationOfBenefit-Inpatient-Facility
        at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshot(Publisher.java:4277)
        at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshots(Publisher.java:4222)
        ... 4 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -25
        at java.lang.String.substring(String.java:1931)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.fixedPathSource(ProfileUtilities.java:2001)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:841)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:894)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:1019)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:1218)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:865)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:865)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.processPaths(ProfileUtilities.java:865)
        at org.hl7.fhir.r5.conformance.ProfileUtilities.generateSnapshot(ProfileUtilities.java:536)
        at org.hl7.fhir.igtools.publisher.Publisher.generateSnapshot(Publisher.java:4275)
        ... 5 more
```
However, when you generate that IG using SUSHI 0.12.7, no such error appears. The only difference I can find between the StructureDefinition generated by SUSHI 0.13.2, and the StructureDefinition generated by SUSHI 0.12.7 is that the 0.12.7 output contains extra elements in the differential that have not themselves changed, but which have changed children. This was a choice we made in 0.12.7 to make differentials non-sparse. But, in 0.13.2, we rolled back this change to make the differential fully sparse per the guidance given [here](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/The.20link.20.22XXX.22.20for.20.22coding.22.20cannot.20be.20resolved). So in this case, it *seems* to us like the sparse differential on this profile causes the IG Publisher to crash.

Repo to reproduce: https://github.com/saulakravitz/carin-bb/tree/saul
Branch: `saul`
Relevant StructureDefinition: CARIN-BB-ExplanationOfBenefit-Inpatient-Facility

**Comment by grahamegrieve** [comment]
I can't reproduce this because the branch doesn't run:

Sushi: error No element found at path item.adjudication[allowedunits] for CARINBBExplanationOfBenefitPharmacy, skipping rule Sushi: error No element found at path item.adjudication[allowedunits].category.coding.code for Sushi: error No element found at path item.adjudication[allowedunits].value for CARINBBExplanationOfBenefitPharmacy, skipping rule (00:05.0570)
Sushi: error No element found at path item.adjudication[allowedunits].reason for CARINBBExplanationOfBenefitPharmacy, skipping rule (00:05.0572)
Sushi: error No element found at path item.adjudication[allowedunits].amount for CARINBBExplanationOfBenefitPharmacy, skipping rule (00:05.0573)

**Comment by saulakravitz** [comment]
Sorry... lots of water under the bridge in a month.  I tagged a stable point for your debug.
https://github.com/saulakravitz/carin-bb/tree/0.1.1

Thx, Saul

**Comment by grahamegrieve** [comment]
now:

Sushi: info  Running SUSHI v0.14.0                                               (00:00.0527)
Sushi: info  Current FSH tank conforms to an IG Publisher context. Output will be adjusted accordingly. (00:00.0528)
Sushi: info  Using configuration file: C:\work\org.hl7.fhir.igs\carin-bbsk\fsh\config.yaml (00:00.0529)
Sushi: info  Checking local cache for hl7.fhir.us.core#3.1.0...                  (00:00.0536)
Sushi: info  Found hl7.fhir.us.core#3.1.0 in local cache.                        (00:00.0576)
Sushi: info  Loaded package hl7.fhir.us.core#3.1.0                               (00:00.0576)
Sushi: info  Checking local cache for hl7.fhir.r4.core#4.0.1...                  (00:00.0577)
Sushi: info  Found hl7.fhir.r4.core#4.0.1 in local cache.                        (00:01.0167)
Sushi: info  Loaded package hl7.fhir.r4.core#4.0.1                               (00:01.0167)
Sushi: info  Importing FSH text...                                               (00:01.0171)
Sushi: info  Preprocessed 5 documents with 31 aliases.                           (00:01.0360)
Sushi: warn  Using "|" to list references is deprecated. Please use "or" to list references. (00:01.0370)
Sushi: File: C:\work\org.hl7.fhir.igs\carin-bbsk\fsh\CPCDE.fsh                   (00:01.0371)
Sushi: Line: 75                                                                  (00:01.0371)
Sushi: warn  Using "|" to list references is deprecated. Please use "or" to list references. (00:01.0372)
Sushi: File: C:\work\org.hl7.fhir.igs\carin-bbsk\fsh\CPCDE.fsh                   (00:01.0372)
Sushi: Line: 78                                                                  (00:01.0373)
Sushi: error Multiple choices of references are not allowed when setting a value. Only the first choice will be used. (00:01.0374)
Sushi: File: C:\work\org.hl7.fhir.igs\carin-bbsk\fsh\CPCDE.fsh                   (00:01.0375)
Sushi: Line: 78                                                                  (00:01.0375)
Sushi: warn  Using "|" to list references is deprecated. Please use "or" to list references. (00:01.0376)
Sushi: File: C:\work\org.hl7.fhir.igs\carin-bbsk\fsh\CPCDE.fsh                   (00:01.0377)
Sushi: Line: 350                                                                 (00:01.0378)
Sushi: warn  Using "|" to list references is deprecated. Please use "or" to list references. (00:01.0379)
Sushi: File: C:\work\org.hl7.fhir.igs\carin-bbsk\fsh\CPCDE.fsh                   (00:01.0379)
Sushi: Line: 435                                                                 (00:01.0380)
Sushi: info  Imported 54 definitions and 5 instances.                            (00:01.0384)
Sushi: info  Converting FSH to FHIR resources...                                 (00:01.0391)
Sushi: info  Converted 12 FHIR StructureDefinitions.                             (00:02.0326)
Sushi: info  Converted 34 FHIR ValueSets.                                        (00:02.0426)
Sushi: info  Converted 8 FHIR CodeSystems.                                       (00:02.0445)
Sushi: info  Converted 5 FHIR instances.                                         (00:02.0802)
Sushi: info  Exporting FHIR resources as JSON...                                 (00:02.0803)
Sushi: info  Exported 59 FHIR resources as JSON.                                 (00:02.0938)
Sushi: info  Assembling Implementation Guide sources...                          (00:02.0939)
Sushi: info  Copied input\pagecontent\index.md                                   (00:02.0964)
Sushi couldn't be run. Complete output from running Sushi : warn  Your ig-data\ig.ini file contains the following deprecated properties: copyrightyear, license, version, ballotstatus, fhirspec, excludexml, excludejson, excludettl, excludeMaps. These are no longer supported in ig.ini and should be removed.  See the  (00:03.0015)

**Comment by grahamegrieve** [comment]
but it works with 0.13.2. So is this resolved?

**Comment by saulakravitz** [comment]
I just built on my laptop with Sushi 0.14.0 and the latest IG Publisher.   So, the issue appears resolved.
thx.
