### ISSUE TITLE
No Expansion for this valueset (local code systems)

### ISSUE THREAD

**Issue by gcangioli** [HL7/fhir-ig-publisher#113]
For most of the intensionally defined value sets based on local code systems the following message is returned "No Expansion for this valueset (not supported by Publication Tooling)".

Initially I had this kind of message only for value set using filters
see e.g. https://github.com/HL7-IT/base/blob/master/input/vocabulary/ValueSet-minsan-esenzioni.xml (see http://www.hl7.it/fhir/build/it-base/site/ValueSet-minsan-esenzioni.html)

Recently the same happens also for value sets that doesn't use filters as for example:

1. https://github.com/HL7-IT/base/blob/master/input/vocabulary/ValueSet-minsan-idStrutture.json (see http://www.hl7.it/fhir/build/it-base/site/ValueSet-minsan-idStrutture.html); Or
2. https://github.com/HL7-IT/base/blob/master/input/vocabulary/ValueSet-istat-titoloStudio.json (see http://www.hl7.it/fhir/build/it-base/site/ValueSet-istat-titoloStudio.html)

there are few cases however where it still works ...

- https://github.com/HL7-IT/base/blob/master/input/vocabulary/ValueSet-istat-dug.json (see http://www.hl7.it/fhir/build/it-base/site/ValueSet-istat-dug.html )

Happy to learn what I need to configure or change ...

**Comment by grahamegrieve** [comment]
You need to clear the terminology cache in \input-cache\txcache

**Comment by grahamegrieve** [comment]
next release will ignore cached entries for code systems contained in the IG itself.

**Comment by gcangioli** [comment]
I cleared the cache and this solved the problem with the intensional value set **without filter** .

for the value set with the filter (https://github.com/HL7-IT/base/blob/master/input/vocabulary/ValueSet-minsan-esenzioni.xml)  the "No Expansion for this valueset (not supported by Publication Tooling)" message is still there...
