### ISSUE TITLE
IG build link example operations to operation definition

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#114]
when an IG includes operation definitions and examples of use of that operation, then there should be a way to tie the examples with the definition. Best case that the examples are validated.

see https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/IG.20for.20operations

**Comment by lmckenzi** [comment]
We believe this is best addressed by specifying input and output profiles for the operation.  These will then show up as links on the OperationDefinition page.  Those profiles can be referenced by the examples and should show up normally (especially now that one instance can be an example of multiple things).

John accepts this as a viable solution.
