### ISSUE TITLE
change icon for DoseandRate

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#118]
in the Snapshot for MedicationRequest
for doseAndRate | ΣI | 0..* | Element | Amount of medication administered

uses the open-folder icon with hover text = "Resource"

propose changing to the Backbone Element icon
 
see this screenshot: https://chat.fhir.org/#narrow/stream/179166-implementers/topic/doseAndRate/near/201856116

**Comment by grahamegrieve** [comment]
fixed
