### ISSUE TITLE
Silent error in CQL translation when there are duplicate canonical URLs in the dependencies

### ISSUE THREAD

**Issue by jasonesteele** [HL7/fhir-ig-publisher#128]
We had a case where one build was being pulled into another IG build as a dependency where the authors had not changed the canonical URL in `config.yml` although they had changed the ID.  I dug through the code and there's a bit where a mapping and reverse mapping of the IDs and canonical URL's is being built and an exception is thrown (CqlSubSystem.loadNamespaces).  

That exception does not appear as an error and does not stop the build, but the contents and the build log are incomplete.  I would expect an informative error in this case.

*Output with a duplicate canonical URL*
```
Initialization complete                                                          (00:14.0245)
Load Content                                                                     (00:14.0246)
Translating CQL source                                                           (00:14.0292)
Translating CQL source in folder (path)(00:14.0293)
Processing Conformance Resources                                                 (00:14.0385)
Terminology server: Check for supported code systems for (url)
```

*Output if no duplicate canonical URL*
``` 
Initialization complete                                                          (00:14.0473)
Load Content                                                                     (00:14.0474)
Translating CQL source                                                           (00:14.0543)
Translating CQL source in folder (path) (00:20.0644)
Translating CQL source in file (file).cql (01:05.0292)
CQL translation completed successfully.                                          (01:06.0755)
Translating CQL source in file (file).cql (02:35.0799)
... // each CQL file
CQL translation completed successfully.                                          (02:35.0952)
Processing Conformance Resources                                                 (02:36.0345)
Terminology server: Check for supported code systems for (url) (02:38.0135)
Generating Narratives                                                            (02:39.0970)
Validating Resources                                                             (02:39.0972)
Processing Provenance Records                                                    (02:39.0975)
Generating Outputs in (path)/build/output      (02:39.0976)
```

**Comment by brynrhodes** [comment]
All the exceptions that occur are logged to the QA output, just not everything makes it to the console logging. Can you check the QA and see if the error is being logged appropriately?

**Comment by jasonesteele** [comment]
There are validation errors to the effect of the following on each of the Library's containing the CQL but because of other 

```error | not-found | Library | No cql info found for (path)```

There is no error that root exception that occurred during CQL processing (duplicate namespaces in dependencies) - I found the root cause stepping through the tool with a Java debugger.  I'm also not able to see anything in the output that indicates what the author should do to resolve it.    There is this output at the bottom of the publisher run:

```Finished. 00:27.0440. Validation output in /Users/jsteel24/projects/cds-diabetes-ig/build/output/qa.html
Errors: 22, Warnings: 41, Info: 24, Broken Links = 417 (00:41.0010)
Done                                                                             (00:41.0011)
jsteel24@local:~/projects/cds-diabetes-ig (binary-adjunct-files) $ echo $?
0
```

But I would expect the tool return a non-zero status code so that the containing scripting will know propagate a failure and fail our automated build job.

**Comment by jasonesteele** [comment]
Note: most of the error and warnings in this particular case are unrelated.

**Comment by brynrhodes** [comment]
Is there somewhere I can repro this? As far as failing the publisher overall, it doesn't seem like this would be an issue that would rise to the level of "fatal" for the publisher, but I agree the fact that the error isn't making it to the QA is an issue. The overall publishing process didn't fail, it just didn't package some of the resources appropriately, which should be reported in the QA. So I can take a look at and fix the issue not showing up in the QA correctly, but I wouldn't be able to fail the build overall, there would need to be some other way that your process looks at the QA output to make that determination.

**Comment by brynrhodes** [comment]
@jasonesteele , any pointers on where I can reproduce this?

**Comment by lmckenzi** [comment]
No response on request on how to reproduce, so closing.  If it's still an issue, feel free to re-open with instructions (and ideally an IG branch) where we can reproduce the problem.
