### ISSUE TITLE
-watch option issues

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#129]
see this Zulip chat for details on how the -watch option leads to diffierent behavior

https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/watch.20option.20behaves.20differently

**Comment by lmckenzi** [comment]
@Healthedata1 is this still an issue?

**Comment by Healthedata1** [comment]
nope, because I never use watch anymore.

Eric

Eric M Haas, DVM, MS
Health eData Inc
35 Crescent Avenue, Sausalito, CA 94965
707.227.2608|Skype: haas.eric1
***@***.***
