### ISSUE TITLE
validator did not detect element must-support = false derived from a profile with element must-support = true

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#130]
The US Core ped vitals e.g. bmi for age are derived from the FHIR vitals profiles .... They were created using the spreadsheet and for several elements the must support cells were blank which apparently led to must-support = false. However the vitals profile defined these elements as must-support = true. 

The issue is that the validator did not catch this (nor did I until looking at the SD directly).

**Comment by grahamegrieve** [comment]
fixed next release
