### ISSUE TITLE
Issue when creating history

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#134]
The creation of history (and assign history=true in resources.json) should depend on 2 factors
1. if it's about one of the artifacts in the spec 
2. AND is not example (exampleBoolean OR exampleCanonical == false).

Seems condition 2 is missing. 
Example: 
https://github.com/ec-ehealth/Build-source/blob/master/input/ImplementationGuide-BeCoreImplementationGuide.json#L447
and the resources.json still says history=true for the provenance's target resource

**Comment by grahamegrieve** [comment]
fixed next release
