### ISSUE TITLE
Would like a slightly better jurisdiction hint in the warning text.

### ISSUE THREAD

**Issue by barabo** [HL7/fhir-ig-publisher#135]
This might be nit-picky, but I spent some time struggling to properly set my IG jurisdiction due to a misleading suggestion.

I saw this warning in `qa.html` (emphasis `^^^` is mine):

```
The resource should declare its jurisdiction to match 
the package id (hl7.fhir.uv.smart-web-messaging, 
jurisdiction = http://unstats.un.org/unsd/methods/m49/m49.htm#001: World)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I thought, no problem - I'll use that value in my sushi `config.yaml` and rebuild.  Unfortunately, that didn't quite work.

I added this line, which is the *literal* suggested value from the warning:
```yaml
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001: World
```

Rebuilding gave me this sushi error:
```
error Error parsing configuration: Nested mappings are not allowed in compact mappings.
  File: fsh/config.yaml
```

Unfortunately, I didn't see the simple fix right away due to my inexperience with the URN code systems.  I then tried all kinds of silly things before I recognized that what I *needed* was very close to what the warning suggested initially.

This worked for me:
```yaml
jurisdiction: http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World"
```

A better suggestion in the error message would have saved me some time, so I looked into the publisher code hoping to whip up a quick PR.  Long story short, I don't see a clean way to transform the jurisdiction hint from `http://unstats.un.org/unsd/methods/m49/m49.htm#001: World` to `http://unstats.un.org/unsd/methods/m49/m49.htm#001 "World"` without doing something hacky in the publisher code, or something magical in the `toString` logic of the `Coding`.  But I still think it would be worth doing.

The line of code in question is below:
https://github.com/HL7/fhir-ig-publisher/blob/f2b3f4d1bf75713d9d489c9cc655dbd096c79e9d/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L3767

**Comment by keerthivasan-r** [comment]
To improve the message, we have to make changes in the [Coding.java](https://github.com/hapifhir/org.hl7.fhir.core/blob/master/org.hl7.fhir.r5/src/main/java/org/hl7/fhir/r5/model/Coding.java) `toString()` method

May be we can add more information?

```java
      public String toString() {
        String base = getSystem();
        if (hasVersion())
          base = base+"|"+getVersion();
        base = base + "#"+getCode();
        if (hasDisplay())
          base = base+": "+getDisplay();
        return base;
      }
```
But, I'm not sure if the return value of the `toString()` method is used elsewhere since it contains distinguished separators in the
value for showing differences 

#### Format

**System|Version#Code:Display**

**Comment by grahamegrieve** [comment]
not changing the generic toString() routine just for FSH, which is only one perspectice

**Comment by grahamegrieve** [comment]
ok fixed next release

**Comment by keerthivasan-r** [comment]
Yeap, I totally understand the decision. Please let me know the approach, we fix it. Thanks
