### ISSUE TITLE
add -v or -version command line option to the IG publisher

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#138]
This would allow the template (and other tools) to check if the IG version is adequate for the template version (and vice-versa).

**Comment by costateixeira** [comment]
@lmckenzi @grahamegrieve can we (a colleague and myself) make a PR for this? Or does this need more discussion?

**Comment by grahamegrieve** [comment]
well, I certainly have no idea what it would do

**Comment by costateixeira** [comment]
@grahamegrieve  We could start with having just that - the version number - like the PR just submitted

**Comment by lmckenzi** [comment]
Confirmed this is now done.
