### ISSUE TITLE
support for producing implementation guides/npm packages with FML-maps

### ISSUE THREAD

**Issue by oliveregger** [HL7/fhir-ig-publisher#14]
[The specification](https://www.hl7.org/fhir/r3maps.html) states that the maps are subject to ongoing maintenance using the FHIR NPM Package "fhir.versions.r3r4" which is maintained on [GitHub](https://github.com/FHIR/r3r4). 

Currently the R3R4 maps are in the standard itself, see [FHIR source github](https://github.com/HL7/fhir/tree/master/implementations/r3maps/R3toR4), background see also [Zulip discussion](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Maps.20np.20mpackage.20for.20R3.20to.20R4.3F).

The fhir-ig-publisher cannot handle plain/text FML maps currently. Enhancement could be that
plain/text FML maps are parsed and provided as StructureMaps for the ig in the process and afterwards standard ig publication/package generation is used.

**Comment by grahamegrieve** [comment]
> The fhir-ig-publisher cannot handle plain/text FML maps currently.

I think that's not correct. *.map should be loaded directly as resources

**Comment by oliveregger** [comment]
The .map resources should be included as plain/text in the npm package? 

I see that org.hl7.fhir.r5.validation.ValidationEngine.loadIg has the behaviour of loading map file directly, but I can't find any reference in fhir-ig-publisher how maps are treated in the publication process and coud not made it work, so any pointers or links appreciated.

**Comment by litlfred** [comment]
a brief scan of the source code, this still seems to be the case.  are there any plans to add this?

**Comment by lmckenzi** [comment]
We don't want .map files in the packages, we want the StructureMaps as packages are supposed to contain resources.  The correct solution is for the .map text to propagate into the StructureMap as the narrative for the StructureMap.  The IGPublisher now does this.  We encourage other publication tools to take the same approach.
