### ISSUE TITLE
FSH_TIMEOUT of one minute is too short

### ISSUE THREAD

**Issue by keithboone** [HL7/fhir-ig-publisher#143]
I've got 143 FSH files, they run in 59s on my local machine, but timeout in FHIR Build system.

Would like timeouts to be able to be controlled by project configuration so that large numbers of files can be accounted for in a build.

**Comment by grahamegrieve** [comment]
fixed next release. Create a file fsh.ini as a sibling to the fsh directory which has the following content:

    [FSH]
    timeout=NN

where NN is in seconds
