### ISSUE TITLE
The 'mustSupport' view doesn't show everything it needs to

### ISSUE THREAD

**Issue by lmckenzi** [HL7/fhir-ig-publisher#147]
When we'd discussed adding a 'mustSupport' view for profiles, we said it needed to do more than just expose the mustSupport elements.  It needs to expose:
- mustSupport elements
- mandatory elements (min>=1)
- modifier elements

That's the set of elements that implementers *must* consider in creating an implementation.  While it's good practice to consider everything, those meeting the criteria above are the ones that implementers MUST consider in writing their code - which is what this view is for.

**Comment by grahamegrieve** [comment]
is this still a problem?

**Comment by lmckenzi** [comment]
Unless you've changed something super-recently, yes.  I would expect implicitRules, modifierExtension, anything with minOccurs!=0 to show up in the view, regardless of whether it's marked as mustSupport.  (And because the view will show things that aren't mustSupport, it needs to show the mustSupport flags too.)

**Comment by grahamegrieve** [comment]
Do you have a test case anywhere?

**Comment by lmckenzi** [comment]
US Core Provenance.  It should show implicitRules and modifierExtension (at root and on agent, but not in entity because entity isn't a modifier, mandatory or mustSupport) because those are modifiers and it should show agent.who because that's 1..x (but not entity.role or entity.what because entity doesn't meet the criteria for inclusion).

**Comment by lmckenzi** [comment]
Proposed algorithm would be as follows:
1. Start at the root for the StructureDefinition snapshot
2. Include all direct child elements that: have mustSupport=true, have descendants with mustSupport=true, have minOccurs >0, are flagged as modifier elements, have slicing declared or are slices.  Also include those that have minOccurs, maxOccurs or invariants that differ from those in the core resource.  If this algorithm would include *no* elements other than 'modifierExtension' (i.e. you're processing a backbone element that was mandatory or mustSupport but no mandatory or mustSupport children), then in addition to modifierExtension, display all elements not inherited from BackboneElement.
3. Iterate for all child elements appearing in the snapshot.

This algorithm will omit all non-mustSupport, non-mandatory elements that don't have to appear in the instance, don't have any constraints that differ from the base resource and that aren't involved in slicing.

**Comment by lmckenzi** [comment]
Note - we should also rename the tab, but that'll be handled on the template side once this change is made.

**Comment by lmckenzi** [comment]
Closing this - superseded by #320
