### ISSUE TITLE
FSH.ini seems to not be working

### ISSUE THREAD

**Issue by keithboone** [HL7/fhir-ig-publisher#158]
Two builds with a fsh.ini in two different places are giving indications that fsh.ini is still not working.  I'm having this problem in two different builds.  I thought I'd reported this earlier, but maybe I forgot to hit submit.

In any case, here's my analysis:

1. Publisher calls runFsh() from initialize() as follows:

    File fsh = new File(Utilities.path(focusDir(), "fsh"));
    if (fsh.exists() && fsh.isDirectory() && !noFSH) {
      runFsh(new File(Utilities.getDirectoryForFile(fsh.getAbsolutePath())));
    }

runFsh() does the following:
  private void runFsh(File file) throws IOException { 
    File inif = new File(Utilities.path(Utilities.getDirectoryForFile(file.getAbsolutePath()), "fsh.ini"));
    if (inif.exists()) {
      IniFile ini = new IniFile(new FileInputStream(inif));
      if (ini.hasProperty("FSH", "timeout")) {
        fshTimeout = ini.getLongProperty("FSH", "timeout") * 1000;
      }
    }

I've also verified that Utilities.getDirectoryForFile() is basically an alias for File.getParent()
  public static String getDirectoryForFile(String filepath) {
    File f = new File(filepath);
    return f.getParent();
  }

So if "fsh" is the name of your fish folder,
So: runFsh(fsh.getParent()) is about the same as runFsh("fsh/..")
and what runFsh then does is create a new File object in inif that is essentially fsh/../../fsh.ini

Completely beside the point from this report, the code also uses a coding anti-pattern that completely obfuscates the meaning
of standard library classes with Utility functions whose meaning is perhaps readily understandable, but I find the following much easier to follow:

    if (fsh.exists() && fsh.isDirectory() && !noFSH) {
      runFsh(fsh.getParentFile());
    }

And this:
    File inif = new File(file.getParentFile(), "fsh.ini"));  
// Which should actually be:     
    File inif = new File(file, "fsh.ini");

**Comment by keithboone** [comment]
Build log shows that SIGTERM is being received after 1 minute:

Run time = Thursday, August 27, 2020 at 4:15:21 AM Coordinated Universal Time (2020-08-27T04:15:21Z)
Package Cache: var/lib/.fhir/packages                                            (00:00.0017)
Run Sushi on /scratch/ig-build-temp-2DMD7X/repo                                  (00:00.0017)
Sushi: info  Running SUSHI v0.15.1 (implements FHIR Shorthand specification v0.13.x) (00:00.0374)
Sushi: info  Current FSH tank conforms to an IG Publisher context. Output will be adjusted accordingly. (00:00.0376)
Sushi: info  Using configuration file: /scratch/ig-build-temp-2DMD7X/repo/fsh/config.yaml (00:00.0377)
Sushi: info  Checking local cache for hl7.fhir.us.core#3.1.0...                  (00:00.0390)
Sushi: info  Did not find hl7.fhir.us.core#3.1.0 in local cache.                 (00:00.0390)
Sushi: info  Downloading hl7.fhir.us.core#3.1.0...                               (00:00.0391)
Sushi: info  Checking local cache for hl7.fhir.r4.core#4.0.1...                  (00:00.0391)
Sushi: info  Did not find hl7.fhir.r4.core#4.0.1 in local cache.                 (00:00.0392)
Sushi: info  Downloading hl7.fhir.r4.core#4.0.1...                               (00:00.0392)
Sushi: info  Importing FSH text...                                               (00:00.0453)
Sushi: info  Preprocessed 54 documents with 1 aliases.                           (00:00.0851)
Sushi: info  Imported 54 definitions and 93 instances.                           (00:00.0932)
Sushi: info  Downloaded hl7.fhir.us.core#3.1.0                                   (00:01.0827)
Sushi: info  Loaded package hl7.fhir.us.core#3.1.0                               (00:01.0936)
Sushi: info  Downloaded hl7.fhir.r4.core#4.0.1                                   (00:03.0293)
Sushi: info  Loaded package hl7.fhir.r4.core#4.0.1                               (00:04.0420)
Sushi: info  Converting FSH to FHIR resources...                                 (00:04.0429)
Sushi: info  Converted 18 FHIR StructureDefinitions.                             (00:05.0710)
Sushi: info  Converted 28 FHIR ValueSets.                                        (00:05.0795)
Sushi: info  Converted 8 FHIR CodeSystems.                                       (00:05.0824)
Sushi couldn't be run. Complete output from running Sushi :                      (01:00.0046)
Note: Check that Sushi is installed correctly ("npm install -g fsh-sushi". On windows, get npm from https://www.npmjs.com/get-npm) (01:00.0046)
Exception: Process exited with an error: 143 (Exit value: 143)                   (01:00.0046)
Publishing Content Failed: Process exited with an error: 143 (Exit value: 143)   (01:00.0047)
                                                                                 (01:00.0047)
Use -? to get command line help                                                  (01:00.0047)
                                                                                 (01:00.0047)
Stack Dump (for debugging):                                                      (01:00.0047)
org.apache.commons.exec.ExecuteException: Process exited with an error: 143 (Exit value: 143)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at org.hl7.fhir.igtools.publisher.Publisher.runFsh(Publisher.java:1484)
	at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:1383)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:674)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:7939)

**Comment by grahamegrieve** [comment]
Fixed next release
