### ISSUE TITLE
Cannot build ig publisher

### ISSUE THREAD

**Issue by azatadha** [HL7/fhir-ig-publisher#17]
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for HL7 FHIR IG Publisher 0.9.39-SNAPSHOT:
[INFO]
[INFO] HL7 FHIR IG Publisher .............................. SUCCESS [25:08 min]
[INFO] org.hl7.fhir.publisher.core ........................ FAILURE [05:35 min]
[INFO] org.hl7.fhir.publisher.cli ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  30:55 min
[INFO] Finished at: 2019-06-25T13:58:27+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project org.hl7.fhir.publisher.core: Compilation failure: Compilation failure:
[ERROR] /C:/Users/andrew.zander/Documents/GitHub/fhir-ig-publisher/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java:[2510,51] cannot find symbol
[ERROR]   symbol:   variable EXT_RESOURCE_INFO
[ERROR]   location: class org.hl7.fhir.r5.utils.IGHelper
[ERROR] /C:/Users/andrew.zander/Documents/GitHub/fhir-ig-publisher/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java:[2873,73] cannot find symbol
[ERROR]   symbol:   variable EXT_RESOURCE_INFO
[ERROR]   location: class org.hl7.fhir.r5.utils.IGHelper
[ERROR] /C:/Users/andrew.zander/Documents/GitHub/fhir-ig-publisher/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java:[3356,75] cannot find symbol
[ERROR]   symbol:   variable EXT_RESOURCE_INFO
[ERROR]   location: class org.hl7.fhir.r5.utils.IGHelper
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by grahamegrieve** [comment]
@jamesagnew any ideas? I know nothing about this error

**Comment by parisni** [comment]
what version are you using. 
I just compiled the project with Apache Maven 3.6.0
without problem

**Comment by grahamegrieve** [comment]
This might have been transient - I must commit and release errors in the core maven package before I can update the publisher for the changes
