### ISSUE TITLE
publisher should be ignoring these errors about extension

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#171]
* The extension http://hl7.org/fhir/StructureDefinition/elementdefinition-defaulttype is unknown, and not allowed here
* The extension http://hl7.org/fhir/StructureDefinition/elementdefinition-xml-name is unknown, and not allowed here
* The extension http://hl7.org/fhir/StructureDefinition/elementdefinition-timeformat is unknown, and not allowed here

**Comment by lmckenzi** [comment]
Believe this is now fixed.  If not, please re-open.
