### ISSUE TITLE
Should `elementdefinition-defaulttype` reference `id` or `type`?

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#172]
In `cda-ccda-2.2`, there are instances of:
```
    <element id="AD.useablePeriod[x]">
      <extension url="http://hl7.org/fhir/StructureDefinition/elementdefinition-defaulttype">
        <valueString value="SXPR-TS"/>
      </extension>
```
Should the `valueString` in the above example reference the profile's `id` or the profile's `type`? In this case, the referenced type's profile has an `id` of "SXPR-TS", while the `type` has "SXPR_TS". Should the above example be changed to use "SXPR_TS" instead?

**Comment by grahamegrieve** [comment]
type. so SXPR-TS
