### ISSUE TITLE
Error about "Duplicate id ClinicalDocument.authenticator"

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#176]
In `cda-ccda-2.2`, all profiles based on `cda-core-2.0` `ClinicalDocument` profile have this error:
`Duplicate id value 'ClinicalDocument.authenticator'`
The profiles don't actually repeat that element ID, so I'm not sure why it's giving this error.
The error says it's for this context: `StructureDefinition/2.16.840.1.113883.10.20.22.1.1: StructureDefinition.snapshot.element[387]`
I noticed that it is complaining about the snapshot element... So, I think this may be an issue with snapshot generation.

**Comment by grahamegrieve** [comment]
That's cause of this, in the differential : 

    <element id="ClinicalDocument.authenticator">
      <path value="ClinicalDocument.authenticator"/>
      <slicing>
        <discriminator>
          <type value="value"/>
          <path value="signatureCode"/>
        </discriminator>
        <rules value="open"/>
      </slicing>
      <short value="The authenticator identifies a participant or participants who attest to the accuracy of the information in the document."/>
      <requirements value="MAY contain zero or more [0..*] authenticator (CONF:1198-5607) such that it"/>
    </element>
    <element id="ClinicalDocument.authenticator">
      <path value="ClinicalDocument.authenticator"/>
      <requirements value="MAY contain zero or more [0..*] authenticator (CONF:1198-5607) such that it"/>
      <min value="0"/>
      <max value="*"/>
    </element>

no slice name on the slice

**Comment by lmckenzi** [comment]
Presume this is resolved.  If not, please re-open.
