### ISSUE TITLE
error on generated narrative is too sensitive

### ISSUE THREAD

**Issue by RichardTON** [HL7/fhir-ig-publisher#189]
When building an IG I get the error "Resource has provided narrative, but the narrative indicates that it is generated - remove the narrative or fix it up" for examples with the following text entry
>
 	<text>
		<status value="extensions"/>
		<div xmlns="http://www.w3.org/1999/xhtml">
			<p>
				<b>Manually Generated Narrative</b>
			</p>
			<p><b>id</b>: aodr-example-notwillingtodonate</p>
			<p><b>date initial registration</b>: 2015-11-18</p>
			<p><b>donation decision</b>: Not willing to be a donor</p>
			<p><b>dateTime</b>: 2017-09-21</p>
		</div>
	</text>

That seems to be too strict. The status is not generated, and the text contains "Manually Generated Narrative" rather than "Generated Narrative".

**Comment by RichardTON** [comment]
For my examples I can just change the first line of the text.

**Comment by grahamegrieve** [comment]
is it generated or manual?

**Comment by RichardTON** [comment]
hand built

**Comment by RichardTON** [comment]
How about just testing for the string "Generated Narrative" when the status is generated ?

**Comment by RichardTON** [comment]
Is this an error from the validator, and applies to all resources or one from the publisher that only applies to publisher transformed resources?
If the first I think it is too strict. If the second, it is OK.

**Comment by grahamegrieve** [comment]
it apples to all resources that provide narrative - it's a check that editors haven't just stored previously generated narrative and used that. Either write your own narrative and call it something like 'example narrative', or anything that doesn't include the words 'generated narrative'
