### ISSUE TITLE
Rendering of Questionnaires should include publication information

### ISSUE THREAD

**Issue by ElliotSilver** [HL7/fhir-ig-publisher#191]
Similar to other definitional resources like StructureDefinitions and ValueSets, Questionnaire rendering should include the publication and versioning information, canonical URL, etc. Currently this can only be seen in the JSON/XML renderings of Questionnaire.

**Comment by grahamegrieve** [comment]
I think this is a template issue

**Comment by costateixeira** [comment]
@grahamegrieve is the status fragment generated for the Questionnaire resources? I don't think it is. If it is, we can resolve this with https://github.com/HL7/ig-template-base/issues/146

**Comment by lmckenzi** [comment]
This is now done.
