### ISSUE TITLE
Not all operation columns are showed on capabilitystatement 

### ISSUE THREAD

**Issue by Steean** [HL7/fhir-ig-publisher#2]
The generated html-page for a capability statement contains a table with all the resourcetypes and the exposed operations for each type. I have been wondering why the `Delete` column was missing for one of my resources. I investigated the issue and it turned out that the last element is the decider for which columns to show. If I manually change the order of the resources in the capability statement I can change the number of columns which will be shown. I have attached two screenshots which shows the issue:

The original order:
![image](https://user-images.githubusercontent.com/5352290/57216286-be2d0880-6fef-11e9-9386-0b7674ac66fe.png)

The changed order:
![image](https://user-images.githubusercontent.com/5352290/57216318-d43ac900-6fef-11e9-9ce6-0e3c142827be.png)

As you can see the number of columns changed when I moved the `StructureDefinition` resource to not be the last resource.

The IG that im working on can be found here: http://ehealth-documentation.s3-website-eu-west-1.amazonaws.com/latest/ig/CapabilityStatement-questionnaire.html

**Comment by grahamegrieve** [comment]
This has been fixed
