### ISSUE TITLE
proxy not actually implemented

### ISSUE THREAD

**Issue by parisni** [HL7/fhir-ig-publisher#20]
hi

while the documentation states a proxy is allowed, the proxy code is commented

**Comment by grahamegrieve** [comment]
what's the actual issue?

**Comment by parisni** [comment]
the issue is the proxy looks not being used. In a network where proxy exist, the program get timeout. In a network not having a proxy, specifying a proxy does not introduce a timeout

**Comment by grahamegrieve** [comment]
I'm afraid your language is confusing me - sounds like setting a proxy works?

**Comment by parisni** [comment]
in short: specifying the proxy has no influence in my tests

**Comment by grahamegrieve** [comment]
The relevant code is :

  String proxy = getNamedParam(args, "-proxy");
      if (!Utilities.noString(proxy)) {
        String[] p = proxy.split("\\:");
        System.setProperty("http.proxyHost", p[0]);
        System.setProperty("http.proxyPort", p[1]);
      }

Line 6273 of publisher.java. Can you check that this is executing. Should be. If it is... I have no idea why it doesn't work...

**Comment by parisni** [comment]
I finally got it working.

The -proxy did not work in my case. However, this worked by running like this:
``` bash
java $$JAVA_OPTS -Xms4g -Xmx8g -Dhttp.proxyHost=<ip> -Dhttp.proxyPort=<port> -Dhttps.proxyHost=<ip> -Dhttps.proxyPort=<port> -jar  ../lib/org.hl7.fhir.publisher.cli-0.9.41-SNAPSHOT.jar -ig ig.json
```
I suspect you have to add this in order the proxy works in your code:

``` java
String proxy = getNamedParam(args, "-proxy");
if (!Utilities.noString(proxy)) {
String[] p = proxy.split("\:");
System.setProperty("http.proxyHost", p[0]);
System.setProperty("http.proxyPort", p[1]);
System.setProperty("https.proxyHost", p[0]);
System.setProperty("https.proxyPort", p[1]);
}
```

**Comment by grahamegrieve** [comment]
thanks. fixed
