### ISSUE TITLE
Invalid XHTML in Generated Narrative for Examples

### ISSUE THREAD

**Issue by prb112** [HL7/fhir-ig-publisher#203]
**Problem**
When an Implementation Guide with an Example without a narrative is compiled, the generated XHTML is invalid.  Consider [MedicationRequest-uscore-mo2.json](https://hl7.org/fhir/us/core/MedicationRequest-uscore-mo2.json.html) from US Core has an invalid generated narrative. 

Referring to [Mozilla: Phrasing Content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content) and [Blockquotes](https://stackoverflow.com/questions/32170760/must-blockquotes-contain-paragraphs-or-must-paragraphs-contain-blockquotes), which states: 

* [Any <p> (or other block-level element) will implicitly close any open `<p>`](https://www.w3.org/TR/html401/struct/text.html#h-9.3.1)
* The P element represents a paragraph. It cannot contain block-level elements (including P itself).

I looked at `Publisher.generateNarratives` which calls: 

```
ResourceWrapper rw = new ElementWrappers.ResourceWrapperMetaElement(lrc, r.getElement());
RendererFactory.factory(rw, lrc).render(rw);
```

Which seems to call custom XhtmlComposer which may generate the invalid XHTML.  

Any guidance or fix would be appreciated. 

**Related Context**
Follow on from [FHIR-28409: Invalid XHTML in Examples MedicationRequest-uscore-mo2 XML/JSON](https://jira.hl7.org/browse/FHIR-28409)

**Comment by grahamegrieve** [comment]
I don't see the invalid XHTML in that example.

**Comment by lmckenzi** [comment]
@prb112 Is this still an issue?    If so, can you provide a specific location where it's occurring?

**Comment by prb112** [comment]
The above example was fixed by that team.  The generated XHTML is not always compliant with the specification. You are welcome to close this as I've moved to a new project.

**Comment by lmckenzi** [comment]
We believe this is now fixed.
