### ISSUE TITLE
trim() throws NPE if tx.getValueSet() == null

### ISSUE THREAD

**Issue by patrick-werner** [HL7/fhir-ig-publisher#204]
https://github.com/HL7/fhir-ig-publisher/blob/0bbf9ec82094f883cec49f791421f223acacf6fc/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java#L585

Occurs in the context of unknown loinc codes by the tx server.

**Comment by grahamegrieve** [comment]
fixed elsewhere
