### ISSUE TITLE
Timeout during narrative generation

### ISSUE THREAD

**Issue by markkramerus** [HL7/fhir-ig-publisher#210]
I'm encountering a timeout on the autobuild. See https://build.fhir.org/ig/HL7/fhir-mCODE-ig/branches/master/failure/build.log

This IG is heavy on terminology (1000's of terms in multiple value sets).

**Comment by lmckenzi** [comment]
@markkramerus has this issue been resolved?

**Comment by markkramerus** [comment]
Autobuild didn't timeout, so let's call it fixed.
