### ISSUE TITLE
Wrong links to metadatatypes in snapshot tables

### ISSUE THREAD

**Issue by Steean** [HL7/fhir-ig-publisher#22]
The generated snapshot tables links to the HL7 datatype page instead of the metadatatype page. 
Eg. http://hl7.org/fhir/STU3/datatypes.html#DataRequirement instead of http://hl7.org/fhir/STU3/metadatatypes.html#DataRequirement. 

See the link to the DataRequirement type in the snapshot table for this resource: http://ehealth-documentation.s3-website-eu-west-1.amazonaws.com/latest/ig/StructureDefinition-ehealth-plandefinition.html.

**Comment by grahamegrieve** [comment]
This is a bug in spec.internals in the core spec, but I can't fix that for a few weeks. Put a hack in the code for that - this is reminder to take the hack out of the code.

**Comment by grahamegrieve** [comment]
All working ok
