### ISSUE TITLE
Publisher using wrong text for short and definition.

### ISSUE THREAD

**Issue by RichardTON** [HL7/fhir-ig-publisher#227]
When a profile defines the types of an element, the IG Publisher replaces the short and definition of the element with values from the first mentioned type, rather than from the base definition.

For example, if PratitionerRole.identifier has its type set to Identifier, AUMedicareProviderNumber, the short is changed from "Business Identifiers that are specific to a role/location" to "An identifier intended for computation".
This can be managed by explicitly setting PractitionerRole.identifier.short to the value that it should inherit from PractitionerRole.

See http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-practitionerrole.html
and https://github.com/hl7au/au-fhir-base/blob/master/resources/au-practitionerrole.xml
This has had the correct text added to the difference.

In [AU Organization](https://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4//StructureDefinition-au-organization.html) address shows the short which is not edited in the differential. It has the text from the Address data type instead of from the Organisation resource.

**Comment by RichardTON** [comment]
@markiantorno

**Comment by RichardTON** [comment]
I've created a rather better demo at http://build.fhir.org/ig/ci-collaborative/au-fhir-base-r4/branches/demo-of-inherited-test/StructureDefinition-au-practitionerrole.html

In the differential there is no short or definition for PractitionerRole.identifier, so I expect snapshot to inherit them from core PractitionerRole.
But, in the snapshot short and definition have values from the Identifier data type rather than from core PractitionerRole.

I want to keep the short and definition from core. To do that I have to include them in differential. That is counter intuitive to me.

**Comment by RichardTON** [comment]
Another example is Location.address at http://build.fhir.org/ig/hl7au/au-fhir-base/StructureDefinition-au-location.html

**Comment by lmckenzi** [comment]
This is actually a HAPI snapshot generation issue.
Raised as https://github.com/hapifhir/org.hl7.fhir.core/issues/914 and closing here.
