### ISSUE TITLE
The outcome of IG publishing depends on the state of txcache 

### ISSUE THREAD

**Issue by markkramerus** [HL7/fhir-ig-publisher#231]
Expected behavior is that given X inputs, the IGP should output a constant Y every time -- and this MUST not depend on the state of temp files, terminology cache, etc.

But this principle is violated with mCODE 1.5.0 (https://github.com/HL7/fhir-mCODE-ig).  With no txcache, I get 67 errors. After the first run (which creates a local txcache), this drops to 2 errors.

Here is what appears to be happening:
- Valueset.expansion isn't populated until the VS is expanded.
- If IGP doesn't know the code system, it can't do the expansion.
- Without the expansion, there are a lot of errors since the VS appears essentially empty. There are slicing errors, unknown codes in examples, and more
However,
- On the first run of the IGP, local codes (defined in local code systems) are cached
- NEXT time the IGP runs, the IGP looks in the cache when it is time to expand the local VS, and lo and behold,
- This results in successful expansion of the value set.
- The errors resulting from empty value set expansions disappear.

**Comment by lmckenzi** [comment]
If a cache is old, then generation with the cache can be different than generating fresh.  However, agree that if a publishing run populates the cache, then that publishing run should be able to take advantage of the same information when validating.

**Comment by lmckenzi** [comment]
@markkramerus Grahame says he hasn't been able to reproduce.  Can you confirm if this is still an issue, and if so, provide the specific steps to reproduce?

**Comment by lmckenzi** [comment]
No response, so presuming closed.
