### ISSUE TITLE
QA Error related Extension.url

### ISSUE THREAD

**Issue by markkramerus** [HL7/fhir-ig-publisher#240]
The IG Publisher is issuing QA errors of the following form:
```
The element Extension.url has a fixed of type uri, which is not in the list of 
allowed types ([http://hl7.org/fhirpath/System.String])
```
This started somewhere around 1.1.60, and it appears to be widespread among multiple IGs. 

See [this zulip](https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/The.20element.20Extension.2Eurl.20has.20a.20fixed.20of.20type.20uri).

**Comment by grahamegrieve** [comment]
fixed elsewhere
