### ISSUE TITLE
Elements named "extension" always show up as "Extension"

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#242]
In CDA there are element combinations of root & extension in `II` data types.
When published, the IG Publisher _always_ shows "extension" as "Extension" in the Description & Constraints field.
I don't think this is appropriate for CDA profiles. This makes sense for FHIR, but not for CDA.

![image](https://user-images.githubusercontent.com/5384694/110395692-703a1f00-8023-11eb-8fe2-efaaf9b5037e.png)

**Comment by grahamegrieve** [comment]
fixed next release
