### ISSUE TITLE
Error Generating Narrative for ParameterDefinition extension

### ISSUE THREAD

**Issue by coxstuart** [HL7/fhir-ig-publisher#243]
I am attempting to create an extension. In this case the value of the extension is a ParameterDefinition. I am attempting to add a measure-parameter-definition extension to the a measure profile. with an example.

This appears to work, sushi compiles successfully, and IG is produced. However when I create an example, it throws an error when the profiler is Generating Narratives for the example.

Error I'm getting is:
Generating Narratives
org.apache.commons.lang3.NotImplementedException: type org.hl7.fhir.r5.model.ParameterDefinition not handled - should not be here

FSH code below, also available here:  https://fshschool.org/FSHOnline/#/share/3bteTXG

```
Extension:      MeasureParameterDefinition
Id:             measure-parameter-definition
Title:          "Measure Parameter Definition"
* value[x] only ParameterDefinition

Profile:        QualityMeasure
Parent:         Measure
Id:             quality-measure
Title:          "Quality Measure"
* extension contains MeasureParameterDefinition named measureParameterDefinition 0..*

Instance:       QualityMeasureExample
InstanceOf:     QualityMeasure
Usage:          #example
Title:          "Quality Measure Example"
* status = #active
* extension[measureParameterDefinition].valueParameterDefinition.name = #measurePeriod
* extension[measureParameterDefinition].valueParameterDefinition.use = #out
* extension[measureParameterDefinition].valueParameterDefinition.type = #Period
```

**Comment by lmckenzi** [comment]
@coxstuart, is this still an issue or has it been fixed?

**Comment by lmckenzi** [comment]
You can't have a value of type ParameterDefinition.  You can only have a valueReference which is constrained to being of type Reference(ParameterDefinition).  Closing this.  Please re-raise if there's a problem when the StructureDefinition is correctly specified.
