### ISSUE TITLE
Get publisher to distinguish different profiles of same resource when applying Liquid rendering

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#244]
See thread here:
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Using.20liquid/near/227542203

At the moment we can't have different liquid templates for different profiles of same resource.
However, this would be very handy in several cases:
1. Producing renderings for custom resources - e.g. 2 Basic resources, but with type "TransactionDefinition" / "DeviceWarranty"
2. Rendering different types of profiles differently e.g. MedicationRequest (order vs instance-order), DeviceDefinition (profiles "SoftwareApplication" vs "ImplantableDevice" vs "Equipment")

Suggestion for implementation: instead of considering the several parameters that may be used (meta.profile vs Basic.code vs MedicationRequest.intent).. simply rely on meta.profile or a standard extension for rendering.

**Comment by costateixeira** [comment]
@lmckenzi

**Comment by lmckenzi** [comment]
@costateixeira will explore whether his needs can be met if the template simply copies all of the artifact .json files into the _data folder prior to invoking Jekyll.  If this works, we can close this one and add a change to the base templates.  Change would be to modify the ant.xml to add an additional step to onGenerate.  (We'd want to grab the 'final' ImplementationGuide.json file though, which might be hard...)

**Comment by costateixeira** [comment]
Can I ask for help with the copying of resource json files to the _data folder? The rest is doable and this should be a simple operation but I don't know where in the ant.xml to place it. @lmckenzi ?

**Comment by costateixeira** [comment]
@lmckenzi i added it at the very end, see HL7/ig-template-base#209

**Comment by lmckenzi** [comment]
Replaced by https://github.com/HL7/fhir-ig-publisher/issues/581
