### ISSUE TITLE
Copyright date in footer

### ISSUE THREAD

**Issue by melvapeters** [HL7/fhir-ig-publisher#251]
The date populated may be wrong.  Consider giving an warning in the QA.html or populating "+" behind date.  Discussed on FMG call 2021-04-07

**Comment by costateixeira** [comment]
Isn't the copyright date simply taken from the IG itself? If so, can / should the publisher do anything?

**Comment by lmckenzi** [comment]
Objective is for the publisher to check the date passed in the IG and if you're publishing an IG in 2021 and the copyright says 2019 (as opposed to 2019+), it'll spit out a warning.

**Comment by grahamegrieve** [comment]
Done
