### ISSUE TITLE
When rendering an OperationDefinition: link to inputProfile and outputProfile

### ISSUE THREAD

**Issue by jmandel** [HL7/fhir-ig-publisher#252]
When rendering an OperationDefinition that has an inputProfile and/or an outputProfile, it would be super handy to *link to* these from the rendered view!

**Comment by jmandel** [comment]
For example this page doesn't make it clear that profiled inputs/outputs are in play:

![image](https://user-images.githubusercontent.com/313089/114460081-edb6f900-9ba6-11eb-88dd-0009bcbdb0a2.png)

**Comment by grahamegrieve** [comment]
Fixed next release
