### ISSUE TITLE
Error when ElementDefinition.type != StructureDefinition.type

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#258]
`Extension http://hl7.org/fhir/cda/ccda/StructureDefinition/2.16.840.1.113883.10.20.22.4.140 is for type Act, but the Section.entry.act element has type http://hl7.org/fhir/cda/StructureDefinition/Act`

**Comment by grahamegrieve** [comment]
Can tyou provide additional info here - what's the actual problem?

**Comment by seanmcilvenna** [comment]
I believe this is because the ElementDefinition.type.code for cda is the canonical url of the type, but the StructureDefinition.type is just "Ovservation", for example, instead of a full canonical url.. I'll find an example that demonstrates this when at a computer next.

**Comment by seanmcilvenna** [comment]
See this: https://github.com/HL7/cda-ccda-2.2/blob/3c6b19225735ce45e2503b5e17b51de2ed4046e4/input/resources/structuredefinition/2.16.840.1.113883.10.20.22.2.20.xml#L127

And this: https://github.com/HL7/cda-core-2.0/blob/bd615ccb4d223a377921321e0f54ff3e2be762f4/input/resources/Observation.xml#L23

**Comment by grahamegrieve** [comment]
fixed next release

**Comment by ajagann1** [comment]
No longer in the list of current errors.
![image](https://user-images.githubusercontent.com/16195928/140552000-32857d99-5f3a-41b1-a0a5-e1f3c88a1a75.png)
