### ISSUE TITLE
Binding shows in differential but not in snapshot

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#259]
See https://build.fhir.org/ig/HL7/cda-ccda-2.2/StructureDefinition-2.16.840.1.113883.10.20.22.4.128.html as an example.
The slice on `value:value1` shows that it has a binding in the differential table, but not in the snapshot table.

**Comment by grahamegrieve** [comment]
fixed

**Comment by ajagann1** [comment]
![image](https://user-images.githubusercontent.com/16195928/140396801-480ae0d8-8f00-46d5-9fd5-d21d4c5d6850.png)
