### ISSUE TITLE
Bundle examples do not receive a correct URL in artifiact index.

### ISSUE THREAD

**Issue by RobinGroepT** [HL7/fhir-ig-publisher#266]
When I add a Bundle example, it is correctly listed in artifact index but the created hyperlink on the artifact index page ends with .../null (It is processed though by the publisher and is shown in the QA overview)

**Comment by lmckenzi** [comment]
Is there an IG in a publicly available Git repository that demonstrates the issue?

**Comment by lmckenzi** [comment]
Found and submitted PR to fix.  Sorry for causing grief.  (Note - a related fix just pushed to the 'current' base publishing template will mean that the Bundle won't show in the artifact list at all now, rather than showing up with a broken link.)
