### ISSUE TITLE
Show information about XML extensions

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#267]
Some elements in the cda-core-2.0 IG (CDA logical model) include extra information for how it should be processed in XML format, such as:
* elementdefinition-namespace
* elementdefinition-xml-name
For example:
```
<element id="Patient.sdtcRaceCode">
  <extension url="http://hl7.org/fhir/StructureDefinition/elementdefinition-namespace">
	<valueUri value="urn:hl7-org:sdtc"/>
  </extension>
  <extension url="http://hl7.org/fhir/StructureDefinition/elementdefinition-xml-name">
	<valueString value="raceCode"/>
  </extension>
  <path value="Patient.sdtcRaceCode"/>
  ...
</element>
```
This information should be shown to readers of the CDA Logical Model IG (at least) under the Detailed Descriptions tab. It would be good if there were a way to represent this information on the differential/snapshot tables, too, though. Perhaps as another line in the "Description & Constraints" column...
For example:
| Name | Flags | Card. | Type | Description & Constraints |
| ------- | ------ | ----- | ----- | ------------------------------ |
| sdtcRaceCode | | 0..* | CE | *XML Element Name:* raceCode<br />*XML Namespace:* urn:hl7-org:sdtc |

Or maybe...

| Name | Flags | Card. | Type | Description & Constraints |
| ------- | ------ | ----- | ----- | ------------------------------ |
| sdtcRaceCode | | 0..* | CE | *XML:* raceCode (urn:hl7-org:sdtc) |

**Comment by grahamegrieve** [comment]
Done next release

**Comment by ajagann1** [comment]
![image](https://user-images.githubusercontent.com/16195928/140395124-eb8941aa-b8d0-49fa-af8f-d0b0e6e96255.png)
