### ISSUE TITLE
Representing primitive CDA data-types

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#270]
Sean:
> Can you use StructureDefinition to define a simple/primitive type? reviewing the cda-core-2.0 logical model, and finding that things like Performer2.typeCode in CDA/RIM is of type "cs", but in the FHIR logical models for CDA, it's of type "code". A bit of a disconnect there. CS is a complex type, cs is a simple type with restrictions. So, seems like there should be a definition for cs in the CDA logical model that accounts for those restrictions, and then Performer2.typeCode (for example) should be updated to point to that simple type.

Grahame: 
>  no, you can't. Agree that that creates a problem

**Comment by grahamegrieve** [comment]
No tooling changes necessary. I committed a demo for how to set this up for Performer2.typeCode; someone else will have to make the same kind of changes in all the relevant places
