### ISSUE TITLE
Error Jira-Spec-Artifacts  improvement

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#271]
The error from the IG Publisher

`There is no jira specification file defined with the expected name of FHIR-us-odh in the xml folder of the https://github.com/HL7/Jira-Spec-Artifacts project. This must exist before ballot or publication.
`

should point at the article that describes how to fix this. I think it is
https://confluence.hl7.org/display/HL7/Configuring+Specification+Feedback

**Comment by lmckenzi** [comment]
Can you raise this against the HL7 IG template instead of the publisher?  That's where this error is generated from.
