### ISSUE TITLE
ig-publisher strictness on package-list.json

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#286]
I didn't understand till today that the package-list.json needs to be strictly json. I had extra spaces prior to the ':'. I didn't learn this until the second release, and only looking at the qa results. Could this be detected sooner? Could this throw an error, rather than just a note in the qa report (the note is a good note, but didn't pop out at me as a problem).

**Comment by lmckenzi** [comment]
@JohnMoehrke to verify if this is still happening with publication-request.json.

**Comment by JohnMoehrke** [comment]
publication-request.json works with both a leading space before`:` and not. (also works with no trailing space after the `:`.)
