### ISSUE TITLE
Creating broken US Core links

### ISSUE THREAD

**Issue by minigrrl** [HL7/fhir-ig-publisher#295]
I have a dependency on the latest version of US Core: 
```
<dependsOn id="hl7fhiruscore">
        <uri value="http://hl7.org/fhir/us/core/ImplementationGuide/hl7.fhir.us.core"/>
        <packageId value="hl7.fhir.us.core"/>
        <version value="4.0.0"/>
    </dependsOn>
```
This is creating links in the profiles that have a US Core base profile that appear to be wrong: http://build.fhir.org/ig/HL7/vr-common-library/StructureDefinition-Patient-mother.html (See the link at "This structure is derived from USCorePatientProfile).

The IG publisher (I presume it's the IG publisher) is setting the link to: http://hl7.org/fhir/us/core/STU4.0.0/StructureDefinition-us-core-patient.html and it looks like the link should be: http://hl7.org/fhir/us/core/STU4/StructureDefinition-us-core-patient.html.

Another thing to note is that the IG Publisher is not picking up that the link is bad...

@markiantorno - we are hoping to publish this IG in the next week or so, so this is important to get fixed.

**Comment by markiantorno** [comment]
https://github.com/hapifhir/org.hl7.fhir.core/pull/560

**Comment by markiantorno** [comment]
@minigrrl what is the easiest way for me to test this?

**Comment by lmckenzi** [comment]
Seems to now be fixed.
