### ISSUE TITLE
narrative with OID url

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#296]
The IG build is auto generating narrative with an assumption that all datatypes of URL are clickable. Need a way to tell it (for a specific example) that it is just a URI.

IHE has a profiled operation that have parameters where one can pass in (among other thigns) a system value as a string URI. The examples put in an example URI (not url).
The auto generated narrative presumes that the URI datatype is pointing at a browseable URL.

https://github.com/IHE/ITI.PIXm/tree/master

specifically THIS example
http://build.fhir.org/ig/IHE/ITI.PIXm/branches/master/Parameters-pixm-request-mohralice-red-to-blue.html

specifically we do want to allow a system value to be a URN:OID

** Should we have a set of root OIDs that are example OIDs? Much like we have support for a set of fake DomainNames for URLs like http://www.example.org. **

**Comment by lmckenzi** [comment]
John confirms it's fixed
