### ISSUE TITLE
Relative Links in Extensions are not resolvable in Profiles where this extension is used

### ISSUE THREAD

**Issue by oliveregger** [HL7/fhir-ig-publisher#297]
In the IG which is located at https://github.com/ahdis/ch-ig/tree/ampersand [qa.html](https://build.fhir.org/ig/ahdis/ch-ig/branches/ampersand/qa.html) shows the error:

StructureDefinition-TestExt-definitions.html#/html/body/div/div/div/div/div/table/tr/td/p/a at Line 478, column 371	error	The link 'questionnaire.html' for "Questionnaires" cannot be resolved.

The link 'questionnaire.html' originates from the comment in the [ordinal value Extension](http://hl7.org/fhir/extension-ordinalvalue.xml.html) which is included in this observation. This is a relative link and the relative link is kept when it is added into the Observation and can then not be resolved because it is not relative to the FHIR spec. It should be transformed to an absolute url.

For other elements the conversion is done, e.g. Observation.hasMember.  There the link is changed to `[QuestionnaireResponse`](http://hl7.org/fhir/R4/questionnaireresponse.html), event though in the base spec master format definition it is also `[QuestionnaireResponse`](questionnaireresponse.html). 

See also https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/White.20html.20pages.20for.20Profile.20on.20Observation.20with.20ordinal.20Ext

**Comment by lmckenzi** [comment]
There have been a number of fixes to handling relative links.  Is this still an issue @oliveregger?  If so, please point to a CI-build for the IG.

**Comment by oliveregger** [comment]
thanks, looks good locally, will check as soon as sushi based ci builds are running again (ssl cert issue)

**Comment by oliveregger** [comment]
error is [fixed](http://build.fhir.org/ig/ahdis/ch-ig/branches/ampersand/qa.html#_scratch_ig-build-temp-5OG3LO_repo_input_resources_structuredefinition_TestAmpNamed), thanks and and will close this issue
