### ISSUE TITLE
Url Fragment missing value[x] in Differential Tab when including ordinal Extension

### ISSUE THREAD

**Issue by oliveregger** [HL7/fhir-ig-publisher#298]
In the IG which is located at https://github.com/ahdis/ch-ig/tree/ampersand qa.html shows the error:

StructureDefinition-TestExt.html#/html/body/div/div/div/div/div/div/div/div/div/table/tr/td/a at Line 521, column 809	error	The link 'StructureDefinition-TestExt-definitions.html#Observation.valueCodeableConcept.coding.extension:ordinalValue' for "ordinalValue" cannot be resolved (valid targets: 115 targets)

The url cannot be resolved because the fragment  on the differential table is not corresponding to the defined fragment on the detailed description tag, in the detailed description tag there is additional .value[x]. This is occuring in the Differential Table Link by clicking on ordinalValue, but not in the Snapshot view, I think the Differential needs to be fixed. 

Differential link/fragment for ordinalValue: StructureDefinition-TestExt.html#Observation.valueCodeableConcept.coding.extension:ordinalValue
Snapshot link/fragment for StructureDefinition-TestExt-definitions.html#Observation.value[x]:valueCodeableConcept.coding.extension:ordinalValue

**Comment by lmckenzi** [comment]
@oliveregger - is this still an issue?  If so, is there a place where the CI-build of the IG can be found?

**Comment by oliveregger** [comment]
thanks, looks good locally, will check as soon as sushi based ci builds are running again (ssl cert issue)

**Comment by oliveregger** [comment]
error is [fixed](http://build.fhir.org/ig/ahdis/ch-ig/branches/ampersand/qa.html#_scratch_ig-build-temp-5OG3LO_repo_input_resources_structuredefinition_TestAmpNamed), thanks and and will close this issue
