### ISSUE TITLE
ServiceReqeust link not updating

### ISSUE THREAD

**Issue by dadmbc** [HL7/fhir-ig-publisher#305]
The Publisher 'should change the link* to be specific to the R4 spec rather than the IG' is not working properly, causing this build error 'The link 'valueset-diagnostic-requests.html' for "here" cannot be resolved'. 

See for context: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/ServiceRequest.20'valueset-diagnostic-requests.2Ehtml

**Comment by lmckenzi** [comment]
QA issue no longer appearing, so presume this has been addressed by fixes to the publisher.  If there's still an issue, please re-raise with a branch that triggers the problem.
