### ISSUE TITLE
Request to support custom output directories using ig.ini

### ISSUE THREAD

**Issue by OliverCardoza** [HL7/fhir-ig-publisher#318]
I do not think this is supported at the moment but I'd love to be wrong :)

The current defaults seem to have the publisher generate files in the `output/` directory. This appears to be hardcoded in some of the publishing paths. I've been following fshschool.org which uses an `ig.ini` in the tutorial so I've restricted this issue to the publishing process via `-ig` flag. In that flow the path appears to be hard-coded:

[Publisher.initializeFromIg](https://github.com/HL7/fhir-ig-publisher/blob/0709e7ac0fa90dd6ebb005a71b50ab0dc7de008b/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L1752)
```java
  private void initializeFromIg(IniFile ini) throws Exception {
    // ...
    outputDir = Utilities.path(rootDir, "output");
    // ...
  }
```

I haven't traced through much of the code but I wonder if it could be as simple as changing to:
```java
  private void initializeFromIg(IniFile ini) throws Exception {
    // ...
    String igOutput = ini.getStringProperty("IG", "output");
    outputDir = Utilities.path(rootDir, igOutput == null ? "output" : igOutput);
    // ...
  }
```

[EDIT]: The reason I'm interested in a custom output directory is so I can publish an IG using Github Pages. This supports serving the generated HTML using either a separate repo branch (e.g. `docs`) or from the `/docs` folder from the default branch. My preferred solution at the moment is to generate the IG HTML into `/docs` and configure Github pages to serve from there: [Github Pages documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).

**Comment by grahamegrieve** [comment]
It's not supported. We've decided as a community that there's no value in allowing for this to be configured. Why do you think it's a good idea?

**Comment by OliverCardoza** [comment]
@grahamegrieve you're too fast! See the edit in main comment. My workaround is to configure Github pages to serve the entire repo contents.

**Comment by grahamegrieve** [comment]
You don't want to use the ci-build process? (https://github.com/FHIR/auto-ig-builder/blob/master/README.md)

**Comment by OliverCardoza** [comment]
I'm working on a private project at the moment so it doesn't seem like that will work for us.

In hindsight it's trivial to just wrap the Java publisher in a script which runs `mv output docs` after generation. So I'm happy to close this.
