### ISSUE TITLE
Add FSH view to publisher

### ISSUE THREAD

**Issue by saulakravitz** [HL7/fhir-ig-publisher#331]
The rendering of many examples by the IG Publisher is incomplete and/or unhelpful.
For an example of an unhelpful rendering, and our current workaround see http://hl7.org/fhir/us/davinci-pdex-plan-net/InsurancePlan-AcmeQHPBronze.html#notes. 
We suggest that a rendering of each example in FSH (using GoFSH to generate the flattened FSH) be includes (optionally) with each instance.   
A more specific example is the rendering of Capability Statements were we suggest incorporating the functionality embodied by Eric Haas's tools (used to generate the US Core capability Statement renderings) into the publisher pipeline.

**Comment by lmckenzi** [comment]
We will explore adding FSH as an additional tab (that can be turned on and off by the IG author).  We will need to investigate how practical it is to invoke GoFSH from within the renderer.  We will *not* replace narrative generation with FSH.  There is a parallel Git issue that will be coming that will deal with enhancing CapabilityStatement rendering.

**Comment by saulakravitz** [comment]
The only deficit in GoFSH (an option is being added to address this, but delivery date is unclear) is that there are aliases in the output.   In generating the FSH annotation for mCODE I wrote a little[ ruby script](https://github.com/HL7/fhir-mCODE-ig/blob/master/input/images/fshtomd.rb) that dealiased the GOFSH-generated files.  I have no expectations you would use it, but it *might* provide some illumination.

**Comment by lmckenzi** [comment]
@saulakravitz - is the option now added?  We're wondering if this is ready to experiment with yet

**Comment by saulakravitz** [comment]
@lmckenzi   Yes!  The --no-alias. option does the trick.

**Comment by lmckenzi** [comment]
We're ready to see the output of GoFSH for a representative set of IGs that will help verify:
- will performance scale?
- will we hit issues with converting different types of IGs?
- will the artifacts be readable/useful?  (It could be that we'll decide this is valuable for certain resources but not others)

Specific IGs we'd like to see tested: SDC (variety), THO (size/performance), tools (funky logical models), ips, ipa, mhd

Lloyd will seek volunteers on the Shorthand stream to run these and share the output.  (We'll want one file per resource page - where contained resources should be in the file of the containing resource.)

**Comment by costateixeira** [comment]
Just for scope, gofsh cannot run on the source because gofsh only processes JSONs. Probably need to identify the JSONs  in the output that we do gofsh on. Or we exclude the other JSONs.

**Comment by saulakravitz** [comment]
Yes, run gofsh on the built IG (JSON).   You can run gofsh on the entire output, but you may want to be selective about which fsh outputs you incorporate into the IG.   For [vrdr](https://github.com/HL7/vrdr/blob/master/tools/fshtomd.rb), I skipped "ConceptMap", "StructureDefinition", "ValueSet", "CodeSystem", "CapabilityStatement", "OperationOutcome".   Added zero (or negative) value on these.  The real value is on the examples, IMHO.

**Comment by JohnMoehrke** [comment]
My experience from gofsh on MHD
- reasonable output , in specific folders, for - Extension, Invariants, Mappings, Profiles, ValueSets, CodeSystems, aliases
- reasonable output, grab from instance folder, for - ConceptMap, SearchPrameter, OperationDefinition, CapabilityStatement
- Examples, everything else in instance folder, are reasonable too, but far more messy with contained as independent inline files. All reasonable to follow the inline references, simply we would have to assemble the equivalent file made up of the example and the inlines it references.
- Question on if Bundle examples are clear.

**Comment by saulakravitz** [comment]
@JohnMoehrke here is a bundle example:   http://hl7.org/fhir/us/vrdr/Bundle-DeathCertificateDocument-Example1.html

**Comment by cmoesel** [comment]
> We'll want one file per resource page - where contained resources should be in the file of the containing resource.

GoFSH can output a file-per-definition, but I don't _think_ it groups contained resources w/ the containing resource. One issue there is that if a resource is contained by multiple other resources, we would end up w/ duplicate definitions of the contained ("inline") resource.  That said, we could consider some creative approaches to make this work.

**Comment by lmckenzi** [comment]
A resource *can't* be contained by multiple other resources.  You might have identical content, but it would be, by definition, a different resource.

**Comment by cmoesel** [comment]
Right, good point.  Contained resources don't exist / have identity outside of the containing resource.  In the case of FSH, however, you can define an "inline" resource once and apply it in multiple places -- so that's what I really meant.

**Comment by lmckenzi** [comment]
Understand.  Sort of a difference between "what's desired for authoring" vs. "what's desired for rendering".  Obviously we'd want the latter for this.

**Comment by costateixeira** [comment]
One option could be a.standard extension in each resource that contains the fish source. Even better, an individual file that is generated for each instance by sushi, and the publisher picks it up. This file simply contains all that is needed for generating the specific resource. Not sure aboult aliases and rulesets.

**Comment by lmckenzi** [comment]
Jose was a bit ambitious :)

**Comment by lmckenzi** [comment]
We think this is primarily relevant for IG authors, and for them, the original FSH files are much more useful than what GoFSH spits out.  They can find the Git URL for a given spec by going to the CI build and then browse from there.  We don't think that what GoFSH is producing is appropriate/useful to the general audience for IGs.  We won't pursue this one further.
