### ISSUE TITLE
Issue warning/error on use of MS on profile root element

### ISSUE THREAD

**Issue by ElliotSilver** [HL7/fhir-ig-publisher#340]
If a profile marks the root element of the profile as MS (e.g. marking Patient as MS on a profile of Patient, marking Extension as MS on a profile of Extension) then any use of that profile becomes MS. This means that if an extension has defined Extension as MS, anywhere I profile use of that extension, my use becomes MS. This is downright unfriendly to people who want to reuse profiles.

We should throw an error, or at least issue a warning if a profile flags the root element as MS.

**Comment by ElliotSilver** [comment]
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Must.20support.20on.20resource.20root/near/261825057

**Comment by ElliotSilver** [comment]
https://jira.hl7.org/browse/FHIR-34347

**Comment by lmckenzi** [comment]
This will be handled by an invariant on StructureDefinition.  No tooling change required.
