### ISSUE TITLE
Constraints not differentiated by severity (Error vs Warning)

### ISSUE THREAD

**Issue by nickgeorge** [HL7/fhir-ig-publisher#348]
Constraints currently show up in three places (that I am aware of):  The `Constraints` table, the description in the `snapshot`/`differential` tables, and finally in individual field  descriptions links.

However, none of these differentiate whether a constraint is severity Error or Warning.  This is a fairly significant difference, whether or not a constraint is sufficient to mark  resource as invalid, so ideally this would be clearly indicated in all places.

**Comment by lmckenzi** [comment]
Will fix

**Comment by lmckenzi** [comment]
This appears to already be addressed
