### ISSUE TITLE
FHIR Document not rendering as Narrative Content

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#352]
FHIR Document not rendering as Narrative Content even though the narrative being generated and the example is error free according the the ig validator

Here is are two test cases to demonstrate this on a test ig build.

http://build.fhir.org/ig/Healthedata1/sample-ig/branches/test-doc-rendering/Bundle-cdex-electronic-sig-example.html

![image](https://user-images.githubusercontent.com/7410922/145534237-e4fc1fcf-f502-46fd-a08e-4ada02e7ac22.png)

this one has an electronic signature the other does not. 

source repro: https://github.com/Healthedata1/sample-ig/tree/test-doc-rendering/input/examples

**Comment by lmckenzi** [comment]
This seems to work in a couple of IGs we've looked at.
