### ISSUE TITLE
URI validation support for ldap:

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#356]
request that "ldap:" be added as a legitimate URI prefix for uri datatype.

I have a need for recording .system elements that are X.500 names. I have determined that the proper way to convert X.500 names into a URL is to use "ldap://". (also legitimate URI for ldap directories)
    https://datatracker.ietf.org/doc/html/rfc4516

The ldap: method has an additional wrinkle in that it is used when the x.500 directory has no ldap endpoint, thus there would be no hostname in the ldap://{hostname}/{path}. Thus the convention is to use "ldap:///{path}"

see [IG creation chat](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/uri.20rules.3F)

I looked for a URN solution for X.500; but did not find one. Would be glad to switch to that solution.

**Comment by grahamegrieve** [comment]
this is actually a validator issue, not an IG publisher issue. Please provide an example resource with a proper usage, and make an issue against https://github.com/hapifhir/org.hl7.fhir.core/issues
