### ISSUE TITLE
Bundle validation error with profiled content with contained

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#357]
The validator is throwing errors on bundles that I don't think are a problem. They were not identified as a problem a month ago when I published IHE-MHD ig. But now are errors. Investigated this and don't find any encoding problems.

see [IG creation chat](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/new.20Bundle.20validation.20behaviour)

I have isolated the bug. I have created a testBundle IG that isolates the problem. 
- [github repo](https://github.com/JohnMoehrke/testBundle)
- [ci-Build](http://build.fhir.org/ig/JohnMoehrke/testBundle/branches/main/index.html)

The errors are thrown when... I have a Bundle that is profiled, that bundle profile is by #profile, and a resource in the bundle has a contained resource.

See fshFood.fsh. 
- comment out lines 91 and 92 (the contained Practitioner); 
- and no error will be thrown.

note, it does not help for the profile of that resource to mandate contained resource. (line 80)

**Comment by grahamegrieve** [comment]
Fixed next release

**Comment by JohnMoehrke** [comment]
confirmed with 126 is fixed.
