### ISSUE TITLE
Upgrade PlantUML library

### ISSUE THREAD

**Issue by dragos-dobre** [HL7/fhir-ig-publisher#358]
When compiling a PlantUML diagram, the resulting SVG file contains the XML tag. By including the generated SVG file (`{% include name.svg %}`) will make the HTML file to display the XML tag as inline text.

`<p>&lt;?xml version=”1.0” encoding=”UTF-8” standalone=”no”?&gt;<svg contentstyletype="text/css" viewBox="0 0 581 1222" zoomAndPan="magnify" preserveAspectRatio="none" width="581px" style="width:581px;height:1222px;" contentscripttype="application/ecmascript" version="1.1" height="1222px">...</svg></p>` 

![image](https://user-images.githubusercontent.com/20338285/146415556-7ecb9620-71a1-4a8a-b1e9-444a324a7be1.png)

It seems the XML tag is not added in latest version of PlantUML (https://forum.plantuml.net/12443/remove-xml-declaration-from-svg). 

Here is the result for our IG: https://openimis.github.io/openimis_fhir_r4_ig/usecases.html 

Can you please update the PlantUML library? 

Thanks.

**Comment by costateixeira** [comment]
This is addressed with https://github.com/HL7/ig-template-base/pull/189
Can be closed here
