### ISSUE TITLE
scrub front matter from content when running build

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#360]
Since the ig-publisher design requires that content be included ( instead of using [Jekyll layouts](https://jekyllrb.com/docs/layouts/) ) any front matter present in files is rendered in the output. :-( 

Based on ig-publishing WG call which is summarized in this [chat](https://chat.fhir.org/#narrow/stream/196008-ig-publishing.20requirements/topic/bring.20back.20front.20matter!/near/265053601) it was decided to have the ig-publisher scrub front matter from content when running build so that the front matter can still be used outside the ig-publisher.

**Comment by lmckenzi** [comment]
We don't support front matter and don't plan to.
