### ISSUE TITLE
Rendering error in detailed description page for complex extensions

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#366]
The type element list all the option in detailed description page for complex extensions:

for example in US Core Patient Profile:

![image](https://user-images.githubusercontent.com/7410922/147785870-0e2cbe63-e668-4556-9b53-93cd35198423.png)

(http://build.fhir.org/ig/HL7/US-Core/StructureDefinition-us-core-patient-definitions.html)

I suggest it render as  "(Complex)"

**Comment by lmckenzi** [comment]
Seems to now be fixed
