### ISSUE TITLE
Suppress elements output from FHIR IG Publisher for CDA

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#373]
For CDA, we need to suppress the generation of the following elements for each profile:
* Top-level JSON and TTL tabs
* "Snapshot Table (Must Support)" tab in "Formal Views of Profile Content"
* "Other representations of profile: CSV Excel Schematron"

Please make changes to the IG Publisher to support suppressing these elements, or provide instructions on how to influence the IG Publisher to do what we want.

**Comment by lmckenzi** [comment]
Suppressing JSON and TTL can be turned off now.  Take a look at the DaVinci-CRD guide for how we turn off XML and TTL.
Must Support view is changing to be a "key elements" view.  Why would CDA not want that?
Why would CDA not want the CSV or Excel view?  And Schematron is part of the existing CDA tool-stack, so it seems odd to not want that too...

**Comment by seanmcilvenna** [comment]
Good that JSON and TTL can be turned off. Can you confirm that it gets removed from the "Other representations of profile: " list? And, how do we remove CSV and Schematron from those options as well?

CDA does not currently make use of "must support" and has no plans to do so. We have concluded that we would like to consider using it, but in the future, when we have a better understanding of how "must support" relates to historical CDA concepts and when we can provide clear direction to CDA IG developers on when to use must support or not. Until we come up with that clear guidance for CDA IGs in FHIR, we don't want to show an entire tab that describes "must support" that will just be confusing to CDA IG readers.

**Comment by lmckenzi** [comment]
It won't just remove them as hyperlinks, it'll prevent them from being generated.
It makes no sense to remove CSV if you're not removing Excel - and I don't understand why you'd want to remove either.  Analysts like dumping stuff into spreadsheets, databases and other mapping tools.  Why do you want Schematron removed?

When "must support" view changes to "key elements" view, it won't just expose mustSupport, it'll expose mandatories, elements subject to invariants, elements that have been constrained from base, etc.  The name will also change.  Will that make it better?

**Comment by lmckenzi** [comment]
Given no further discussion, presume we can safely close.
