### ISSUE TITLE
Automated generation of changes

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#374]
When publishing a new version of an IG, would be great to have the IG Publisher do a diff of old profiles to new profiles, and generate a concise change list.

**Comment by lmckenzi** [comment]
I *think* it already does this?  However, we might not be properly surfacing the results.  It would also be helpful if we could indicate for profiles whose URLs have changed what the equivalent(s) were in the prior version to support that mapping (and maybe even explicitly declare "this replaces x and y in version 123").

**Comment by grahamegrieve** [comment]
It’s only
Available from the qa page

**Comment by seanmcilvenna** [comment]
The request comes from SDWG (and ITS) requiring that new versions of an IG have a change history so that implementers can see
1. Which profiles have changed
2. Which parts of the profiles have changed (i.e. which elements, new/changed narrative text, etc.) 

Great that the IG Publisher produces something like this already, but would be great to have this in the published IG, not just the QA.

**Comment by lmckenzi** [comment]
We're now generating pages that look like this: https://build.fhir.org/ig/HL7/fhir-extensions/comparison-v1.0.0/index.html that you could link to from elsewhere in your IG if you wish.  There's also the change flag you can set on generation that gives you content that looks like this: https://build.fhir.org/ig/HL7/fhir-extensions/StructureDefinition-obligation.html

No further action to be taken.  If you think more is necessary, please submit a new tracker describing in detail what else is needed.
