### ISSUE TITLE
Create new artifact to list the IG wide invariants as a list or table

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#375]
Currently there is no convienent way to discover an Ig-wide list of invariants.  I propose a new ig-publisher feature:  a summary of invariants as a fragment or table to make this easier to expose to the reader.

**Comment by lmckenzi** [comment]
Can you explain the use-case for why a reader would want this?  Would it contain duplicates?  E.g. every occurrence of every invariant in every profile?

**Comment by lmckenzi** [comment]
No further discussion or requests for this in almost 3 years.  We don't understand the use-case.  Closing for now.  Issue can be re-opened if clearer requirements and justification are provided.
