### ISSUE TITLE
Linking from ValueSet concepts to CodeSystem works for 'complete' CodeSystems only.

### ISSUE THREAD

**Issue by gabriel0316** [HL7/fhir-ig-publisher#376]
If a ValueSet includes some or all values from a CodeSystem which **has not got `CodeSystem.content="complete"`** the linking from the concepts within the ValueSet to the CodeSystem is not working.

Here is an example where the CodeSystem has got `CodeSystem.content="fragment"`. If they are processed by the IG. No links are produced.

CodeSystem:

    {
      "resourceType": "CodeSystem",
      "id": "test-cs",
      "name": "test-cs",
      "title": "Test CS",
      "status": "active",
      "content": "fragment",
      "description": "Test Code System",
      "concept": [
        {
          "code": "1",
          "display": "test01"
        },
        {
          "code": "2",
          "display": "test02"
        },
        {
          "code": "3",
          "display": "test03"
        }
      ]
    }

ValueSet:

    {
      "resourceType": "ValueSet",
      "id": "test-vs",
      "name": "test-vs",
      "title": "Test VS",
      "status": "active",
      "description": "Test Value Set",
      "compose": {
        "include": [
          {
            "system": "test-cs"
          }
        ]
      }
    }

**Comment by lmckenzi** [comment]
@gabriel0316 is this still an issue?

**Comment by ElliotSilver** [comment]
@lmckenzi, it looks like there is a PR associated with this that has been merged. I think we can close.
