### ISSUE TITLE
Apply-* parameters should support "apply if absent"

### ISSUE THREAD

**Issue by ElliotSilver** [HL7/fhir-ig-publisher#377]
In my IG I have a couple of artefacts that have a different copyright than the rest. However, my choices currently are use apply-copyright=true, and the copyright of the IG is copied to all resources; or copyright=false, and I have to manually fill in the copyright on every single resource.

Similarly, in [Zulip chat](https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Profiles.20Versioning/near/268709981), the option of fixing a profile version once it matures, but allowing other profiles to continue to use the IG version number as they are still in development came up.

It would be nice if all the apply-* parameters would only cause an element to be applied if it was absent from a resource. This could be done by changing the behaviour of apply-*=true, but this might affect existing IGs. Instead, I suspect the easiest option is to add support via a third value, perhaps along the lines of "ifMissing" or "whenAbsent".

**Comment by lmckenzi** [comment]
Use the default-copyright.  This will cause the IG copyright to propagate to all artifacts that don't declare a copyright, but will leave the copyright declared on artifacts that have a copyright value already specified.  (Same pattern for all other elements - you can use apply-* or default-* depending on your desired behavior.)
