### ISSUE TITLE
Use a default date format and make date format configurable

### ISSUE THREAD

**Issue by gabriel0316** [HL7/fhir-ig-publisher#378]
Based on https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Configure.20date.20format the IG should have 

`yyyy-mm-dd` 

as default date format regardless of current locale. However, it should also be possible to configure the date format.

**Comment by lmckenzi** [comment]
Based on the Zulip discussion and commit, we believe this is now done.
