### ISSUE TITLE
Allow specifying location of sushi binary via flag

### ISSUE THREAD

**Issue by nickgeorge** [HL7/fhir-ig-publisher#379]
Currently I'm running into a lot of issues with non-engineer folks where their paths aren't set up right and npm install isn't doing the right thing - it would be super nice if we could just put a sushi binary in a shared location and then point the publisher to that, e.g.,
```
publisher.jar --sushi=/my/shared/filesystem/sushi
```

**Comment by lmckenzi** [comment]
https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Publisher.20pointing.20to.20'shared'.20SUSHI.20install.20location

**Comment by lmckenzi** [comment]
@nickgeorge In the Zulip chat, we're struggling to understand exactly what you're looking for and how you're hoping for it to work.  Could you join the discussion there?

**Comment by lmckenzi** [comment]
Based on response from Nick, Docker is sufficient so we will close.
