### ISSUE TITLE
Error in copying dist-hist folders when publishing a release

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#380]
Scenario / description:

* Running the ig publisher in go-publish mode with this command line from the working folder
`java -jar publisher.jar -go-publish -source myig -destination web-root -registry ig-registry/fhir-ig-list.json -history ig-history`

* the ig-history folder has the folders `assets-hist` and `dist-hist`

We get the error 
`History Error: C:\work\ImplementationGuides\workingfolder\web-root\dist-hist doe not exist` 
`History Error: C:\work\ImplementationGuides\workingfolder\web-root\assets-hist doe not exist` 

It's not clear why it's trying to copy from web-root\dist-hist, because the software (correctly?) copies the history template to the destination (in this case, web-root)

Specifically, this line:
https://github.com/HL7/fhir-ig-publisher/blob/master/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGReleaseUpdater.java#L216

checkCopyFolderFromRoot(folder, "dist-hist");  
when the publisher is here, folder has value "C:\............\workingfolder\web-root\core"

So why does it try to copy the folder from the parent folder to that one?

**Comment by JohnMoehrke** [comment]
I am getting a different NPE complaining that {dist-hist path} and destination {dist-hist path} are the same.
- I am using -publish-update, not -go-publish.

**Comment by lmckenzi** [comment]
@costateixeira @JohnMoehrke Is this still an issue?

**Comment by JohnMoehrke** [comment]
I don't think I have seen this in a very long time.

**Comment by lmckenzi** [comment]
We suspect this is no longer an issue.  If you see this again, please raise a new ticket.
