### ISSUE TITLE
references to dicom codes/valuesets go thru simplifier

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#382]
In an IG, when calling on a DICOM valueset, that the IG rendering of that has a redirect thru simplifier.

for example - http://build.fhir.org/ig/HL7/fhir-radiation-dose-summary-ig/StructureDefinition-modality-device.html

The Device.type is bound to the DICOM modality canonical URI; but the rendering skips thru simplifier. 

`</span><a href=\"https://simplifier.net/resolve?scope=fhir.dicom@2021.4.20210910&canonical=http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_33.html\">Modality</a>
`

https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/fhir.2Edicom.20has.20no.20ImplementationGuide.20resource

**Comment by lmckenzi** [comment]
Closed as fixed
