### ISSUE TITLE
support for analytics identifier

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#383]
Some publishing sites would like to have the IG html instrumented for web site analytics. One solution is google analytics. It would be nice if the IG publisher could be given the google analytics ID value, and that the IG publisher would insert the google script and that ID into each page.

**Comment by JohnMoehrke** [comment]
IHE is going to brute force in google analytics using the include header and footer mechanism in the ihe template. 

e.g. https://github.com/IHE/ihe-ig-template/commit/6e975099386e7264c51baf26861ef7573060e00d

surely a more elegant and parameter driven solution can be done at some point.

I will keep this posted on our success or lessons-learned.

**Comment by lmckenzi** [comment]
@JohnMoehrke is this something you still think should be in the publisher rather than in a template?  Is this something we need to put in the standard template?

**Comment by lmckenzi** [comment]
@costateixeira says we already have this capability.  He will document.
