### ISSUE TITLE
ImplementationGuide should be validated if it declares a profile

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#391]
Right now, publisher isn't checking the ImplementationGuide instance against profiles it declares in meta.profile.

E.g. if the profile says "this is a IHE IG" or "this is a OpenHIE" or "this is a multilanguage IG", this may mean some constraints that we'd want to appear on QA or somewhere.

**Comment by lmckenzi** [comment]
@costateixeira to provide a URL for a test IG that shows the issue.

**Comment by costateixeira** [comment]
Withdrawing this because the IG does get validated. I think I did not test it properly before, but I can confirm this works now
