### ISSUE TITLE
http://unknown.org on Mapping tab

### ISSUE THREAD

**Issue by Torin-Shepard-athena** [HL7/fhir-ig-publisher#398]
IG pubblished using spreadsheets show http://unknown.org/mapname on the Mapping tab.

unknown.org is hard-coded in supplementMappings method in IgSpreadsheetParser.java.
Published IG shows Mappings for MapName (http://unknown.org/mapname).
Even if this is removed, a published IG will show Mappings for MapName (MapName) which is redundant.

Why is it assumed all mappings will have a valid URI?  If this is a requirement, where can the URI(s) be specified for the custom mapping column(s) in the profile spreadsheet?

Could a parameter be added to myig.xml to suppress output of (uri) in the header of sections on the Mapping tab?

https://github.com/HL7/fhir-ig-publisher/blob/master/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/spreadsheets/IgSpreadsheetParser.java

``` java
  private void supplementMappings(String name) {

      mappings.put("http://unknown.org/" + mapname, m);
```

**Comment by lmckenzi** [comment]
We are no longer enhancing the spreadsheet mechanism to support new authoring capabilities.  IG authors should migrate to using FHIR Shorthand or one of the other authoring tools.  Other key features such as obligations, additional bindings, etc. will also not be implemented in spreadsheets.  Spreadsheet profile authoring will likely eventually be retired.
