### ISSUE TITLE
FHIR-CDA: Snapshot/differential shows data type as full (and broken) URL

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#4]
https://build.fhir.org/ig/HL7/fhir-cda/StructureDefinition-Guardian.html

I believe that it should be showing "CE: CodedWithEquivalents (V3 Data Type)" (with a link) instead of the full URL "​http://hl7.org/fhir/cda/StructureDefinition/CE".

"CE: CodedWithEquivalents (V3 Data Type)" is the title of the profile that represents CE.

The URL that it's pointing to is broken. The profile for CE exists at https://github.com/HL7/fhir-cda/blob/master/resources/CE.xml, and StructureDefinition-CE.html is being produced. The link is pointing to "CE.html" instead of "StructureDefinition-CE.html".

**Comment by grahamegrieve** [comment]
Fixed in the past.
