### ISSUE TITLE
How to generate IG version history HTML page ?

### ISSUE THREAD

**Issue by lquanx** [HL7/fhir-ig-publisher#407]
According to[ this document](https://build.fhir.org/ig/FHIR/ig-guidance/using-templates.html), package-list.json file could provide version history information. 

Can publisher.jar read local package-list.json file and generate history.html page like [this one](http://hl7.org/fhir/us/odh/history.html) ?

Thanks very much !

**Comment by lmckenzi** [comment]
The history page is generated using the publisher go-publish option.  This is done as part of publishing a release.

**Comment by dbojicic** [comment]
@lquanx, we do this in Australia, steps to setup are here: https://confluence.hl7.org/display/HAFWG/Step+By+Step%3A+running+publisher+-go-publish
