### ISSUE TITLE
generated html page title needs IG version not FHIR version

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#411]
Today the title on each page is made up of the title of that page and the FHIR version. This is less helpful than the title of the page and the IG name and version.

This is especially important for google analytics that use the title, and thus the reporting is less helpful between the variations of the IG including the CI-build.

The FHIR version is not a problem, but is less helpful than the IG name and version.

**Comment by lmckenzi** [comment]
Already done.
