### ISSUE TITLE
Update rendering of OperationDefinition to include the overloads element

### ISSUE THREAD

**Issue by rob-reynolds** [HL7/fhir-ig-publisher#412]
**Is:**  
Given the following:
```
<OperationDefinition>
...
    <overload>
        <parameterName value="periodStart"/>
        <parameterName value="periodEnd"/>
        <parameterName value="measureId"/>
        <comment value="These are the parameters used to invoke the operation on a type, i.e., URL: [base]/Measure/$evaluate-measure"/>
    </overload>
    <overload>
        <parameterName value="periodStart"/>
        <parameterName value="periodEnd"/>
        <comment value="These are the parameters used to invoke the operation on an instance, i.e., URL: [base]/Measure/[id]/$evaluate-measure"/>
    </overload>
 ...
 </OperationDefinition>
```

The result of running the publisher does not include the overload information.

**Should be:**
The overload information is rendered.

There is a full explanation and example in the following Zulip Topic: https://chat.fhir.org/#narrow/stream/179239-tooling/topic/Presentation.20for.20OperationDefinition.2Eoverload

This is related to the kindling issue: https://github.com/HL7/kindling/issues/66.

**Comment by lmckenzi** [comment]
@rob-reynolds is there an example of an Operation that uses overloads we can check to see if this is resolved, and if not, that can be used in testing the enhancement?

**Comment by lmckenzi** [comment]
We agree this is needed, however without an example to test against, the work is unlikely to be prioritized.

There's no example in the linked Zulip of an OperationDefinition in an IG with this issue.  And the FHIR CI-build link provided does not (any longer?) include overloads in its OperationDefinition.  We're closing this for now.  Happy for it to be re-opened with a link to a current build or branch showing the issue.
