### ISSUE TITLE
asciidoc support in additional to markdown support for writing the documentations

### ISSUE THREAD

**Issue by kinsonho-arterys** [HL7/fhir-ig-publisher#423]
asciidoc is an alternative markup language for writing documents. It is designed to support writing more complex documents, while keeping a simple syntax for simple common markups similar to markdown. For IG purposes, asciidoc provides several benefits such as better complex table support, document import so that you can easily create one full document while still breaking down different parts as document sub-documents, export to multiple formats such as pdf, epub, html, etc.

Github also supports both markdown and asciidoc. So we can continue to see the rendered document in Github.

For more details, see
- https://asciidoc-py.github.io/index.html
- https://docs.asciidoctor.org/asciidoc/latest/

**Comment by grahamegrieve** [comment]
umm, what does this task seek? I believe that asciidoc is already supported

**Comment by kinsonho-arterys** [comment]
If asciidoc is already supported, that would be good. I thought the IG Publisher only supports documentations written in markdown.

Does it mean in order to use asciidoc, in sushi-config.yaml, under 'pages', I can specify asciidoc instead of markdown for the generation attribute?

**Comment by grahamegrieve** [comment]
Here's an example, I believe: https://github.com/HL7/FHIRPath. I don't know how you use asciidoc - it's a Jekyll question so far as I know, not an IG publisher question

**Comment by lmckenzi** [comment]
No discussion for past 2 years.  Assuming safe to close.  Please re-open if this is still an issue (with more details).
