### ISSUE TITLE
Feature: allow the timeout for Jekyll to be configured

### ISSUE THREAD

**Issue by rob-reynolds** [HL7/fhir-ig-publisher#429]
There are production content IGs that require Jekyll processing that exceeds the 5 minute default.  Allow the value to be configured.

Draft PR: https://github.com/HL7/fhir-ig-publisher/pull/428

**Comment by lmckenzi** [comment]
@rob-reynolds is this now addressed?  You closed your PR, but it's not clear from the comments why.

**Comment by lmckenzi** [comment]
Addressed.
