### ISSUE TITLE
Hardcoded c://temp path causes FileNotFoundExceptions

### ISSUE THREAD

**Issue by znatty22** [HL7/fhir-ig-publisher#43]
# Issue
There seems to be a hard coded path in the latest ig-publisher release 
```
FHIR IG Publisher Version 1.0.6-SNAPSHOT - Built 2019-12-03T23:11:35.574+11:00 - Git d0d7037eb12c
```
This is causing hundreds of FileNotFoundExceptions:
![image](https://user-images.githubusercontent.com/10283712/70066894-71c49e00-15bb-11ea-9042-11d8328714e6.png)

**Comment by grahamegrieve** [comment]
Fixed and releasing now
