### ISSUE TITLE
add a -gh or -repo parameter to explicitly indicate the github (or other) repository

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#430]
Currently the publisher takes the url from the CI publication url and figures out the github url from there.
In some cases does not work: 
1. whenever the process is run on a dedicated VM, such as github actions
2. when the repo is in another location, e.g. another source control (gitlab?)

For the publish box to correctly indicate the source, if needed, we can add an optional command line parameter -gh or -repo that indicates the actual github (or other) url. If the parameter is ommitted, the current logic would still apply, so this wouldn't have any impact on current process.

**Comment by grahamegrieve** [comment]
I do not trust such a GitHub URL

**Comment by costateixeira** [comment]
Should we rather pass the parameters "repo" and "org" to the publisher? Or we can pass them as part of a config file..
The difficulty with that is that we'd also need to specify whether this is github or gitlab (if we ever want to support gitlab).

Is there another alternative?

**Comment by lmckenzi** [comment]
There's now a command-line parameter for this.  No change needed.
