### ISSUE TITLE
create a zip file for the schematrons

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#435]
As a convenience for those use schematrons, it would be nice to have them zipped into a single file.

**Comment by lmckenzi** [comment]
@Healthedata1 Has this been done?

**Comment by Healthedata1** [comment]
Yes
Eric M Haas, DVM, MS
Health eData Inc
211 S Jefferson St, Napa, CA 94559
707.227.2608
***@***.***
