### ISSUE TITLE
How to specify dependencyList in a template-based approach (without a control file)?

### ISSUE THREAD

**Issue by vrayulu** [HL7/fhir-ig-publisher#439]
We are working on an IG and some of our profiles need to reference another profile's structure definition (which is in a different IG). As per the documentation (https://confluence.hl7.org/pages/viewpage.action?pageId=35718627#IGPublisherDocumentation-DependencyList), we need to specify the depdencyList in the control file.

But we are not using a control file, we have a template-based approach as control file is marked as deprecated (ref: https://confluence.hl7.org/pages/viewpage.action?pageId=35718627#IGPublisherDocumentation-Controlfile). We are using the default template "fhir.base.template" and ig.ini to run the publisher:

`java -jar ./publisher.jar -ig ig.ini`

We are unable to figure out how to specify the dependencyList when there is no control file. Can we provide it in the ig.ini file or in any other file? Please help us on how to refer to dependent IGs.

Thanks in advance.

**Comment by grahamegrieve** [comment]
what do you mean, control file? 

but in general, the dependency list is in the IG resource

**Comment by vrayulu** [comment]
Control file has to be provided as input to the publisher when running it - https://confluence.hl7.org/pages/viewpage.action?pageId=35718627#IGPublisherDocumentation-Runningincommandlinemode. And the control file has an option to specify the dependencyList.

We specified the dependency in the IG resource using the "depdensOn" attribute - https://hl7.org/fhir/R4/implementationguide-definitions.html#ImplementationGuide.dependsOn. But we are getting the below error:

```
org.hl7.fhir.exceptions.FHIRException: Unable to resolve package id ndhm.in#2.0.1
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.fetchTheOldWay(FilesystemPackageCacheManager.java:703)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadFromPackageServer(FilesystemPackageCacheManager.java:221)
	at org.hl7.fhir.utilities.npm.FilesystemPackageCacheManager.loadPackage(FilesystemPackageCacheManager.java:505)
	at org.hl7.fhir.igtools.publisher.Publisher.resolveDependency(Publisher.java:3739)
	at org.hl7.fhir.igtools.publisher.Publisher.loadIg(Publisher.java:3577)
	at org.hl7.fhir.igtools.publisher.Publisher.initializeFromIg(Publisher.java:2653)
	at org.hl7.fhir.igtools.publisher.Publisher.initialize(Publisher.java:2159)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:851)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10043)
```

When we reached out to IG team which we are referring from our IG, they suggested us to add their IG in the dependencyList also (in addition to the IG resource).  As per the HL7 documentation, the dependencyList should be added in the control file (https://confluence.hl7.org/pages/viewpage.action?pageId=35718627#IGPublisherDocumentation-Controlfile). But the documentation also mentions that it is now deprecated.

Request you to suggest how the above error can be resolved.

---------

More details:

this is how we specified "dependsOn" in our IG resource:

```
"dependsOn": [
    {
      "uri": "https://nrces.in/ndhm/fhir/r4/ImplementationGuide/ndhm.in",
      "packageId": "ndhm.in",
      "version": "2.0.1"
    }
  ]
```

**Comment by grahamegrieve** [comment]
indeed, the control file is deprecated, and you tried to do it the right way. The fact that the publisher can't find the package is the actual issue. As the team that maintains the package published it? if so, where?

**Comment by vrayulu** [comment]
Do you mean where the IG (to which we are referring from our IG) is hosted? This is the IG which we are referring to: https://nrces.in/ndhm/fhir/r4/.

and this is the package.json from their IG:
```
{
  "name": "ndhm.in",
  "version": "2.0.1",
  "tools-version": 3,
  "type": "fhir.ig",
  "date": "20220215135245",
  "license": "CC0-1.0",
  "canonical": "https://nrces.in/ndhm/fhir/r4",
  "notForPublication": true,
  "url": "file://C:\\FHIR_ImplementationGuide\\IGCheckout\\ig\\output",
  "title": "FHIR Implementation Guide for ABDM",
  "fhirVersions": [
    "4.0.1"
  ],
  "dependencies": {
    "hl7.fhir.r4.core": "4.0.1"
  },
  "author": "National Resource Center for EHR Standards",
  "directories": {
    "lib": "package",
    "example": "example"
  }
}
```

Please let me know if this is the information you are looking for or any other details.

I am a novice in FHIR, bear with my limited knowledge on the subject...

**Comment by grahamegrieve** [comment]
it's a question for the ndhm team: have they got the package into the package registry?

**Comment by vrayulu** [comment]
Thanks @grahamegrieve . We contacted the NDHM team and they are now working on registering in the FHIR package registry.

As a temporary solution, they suggested us to download their package into local ".fhir" folder and generate the IG. It worked and the references to their profiles got generated properly.
