### ISSUE TITLE
Rendering error in snapshot view for complex extensions

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#441]
see description here: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Type.20constraint.20not.20respected.20in.20complex.20Extension/near/281241699

note the diff view renders as expected

**Comment by lmckenzi** [comment]
Closing based on Zulip thread that asserts this isn't actually broken and Eric giving that a thumbs-up.
