### ISSUE TITLE
Warnings for missing descriptions for Observations and other example resources

### ISSUE THREAD

**Issue by lschmierer** [HL7/fhir-ig-publisher#445]
The IG Publisher Version 1.1.118 (Git# 179a6f4ce35d) gives us a bunch of warnings of missing descriptions
```
WARNING: Unable to find ImplementationGuide.definition.resource.description for the resource Observation/exampleInvUninvLightchainRatioUrine.  Descriptions are strongly encouraged if they cannot be inferred from the resource to allow proper population of the artifact list.
```
As far as I can tell, observations are not supposed to have a description.
What does this warning mean to us?

**Comment by grahamegrieve** [comment]
Ask this question here: https://chat.fhir.org/#narrow/stream/179252-IG-creation.
