### ISSUE TITLE
Profiling: Set a BackboneElement to 0..0 - child data elements are NOT set to 0..0

### ISSUE THREAD

**Issue by joepaquette** [HL7/fhir-ig-publisher#446]
When profiling a resource, set the cardinality of a data element having the BackboneElement type to 0..0. Execute the IG Publisher. 

The child data elements of the changed BackboneElement in the generated StructureDefinition for the profile all have their cardinality values matching their base values rather than getting changed to 0..0 based on the parent data element. In the generated IG, the tree view correctly excludes the Backbone data element and all of it children. However, the "Detailed Definitions" page correctly shows the parent's cardinality as 0..0 but all of the child data elements still have their base cardinalities rather than 0..0. 

If a parent (BackboneElement type) data element has its cardinality set to 0..0, all child data elements should have their cardinalities automatically set to 0..0. This needs to be done in the snapshot.element in the generated StructureDefinition. I'm assuming the generated StructureDefinition is used to generate the profile pages in the IG. If this is NOT the case, the IG Publisher will also need to be modified to correctly set the child data elements' cardinality to 0..0 when the parent BackboneElement is set to 0..0.

Consumers of these generated StructureDefinitions (tool's etc.) should not have to know about or have special processing to deal with these invalid child cardinalities. 

To demonstrate this issue, run the [SUSHI Tutorial](https://fshschool.org/docs/tutorials/basic/) for the FishExampleComplete project. The FishPatient.fsh has set the Patient.communication's (a Backbone data element) cardinality to 0..0. Run the IG Publisher and review the FishExampleComplete/output/StructureDefinition-fish-patient.json and notice the cardinalities "Patient.communication" and all of its child data elements. Also review the FishExampleComplete/output/StructureDefinition-fish-patient-definitions.html#Patient.communication Detailed Definition and all of its child data elements.

**Comment by grahamegrieve** [comment]
please start a thread on the #conformance channel on chat.fhir.org to discuss this.

**Comment by joepaquette** [comment]
Based on discussion in Zulip:

- https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/Profiling.3A.20Set.20a.20BackboneElement.20to.200.2E.2E0
- https://chat.fhir.org/#narrow/stream/179177-conformance/topic/Profiling.3A.20Set.20a.20BackboneElement.20to.200.2E.2E0

Closing this issue.
