### ISSUE TITLE
'list-simple' fragments should be ordered by title, rather than by id or random

### ISSUE THREAD

**Issue by rhausam** [HL7/fhir-ig-publisher#467]
In the IPS IG we have some relatively large lists that are being generated by the 'list-simple' code fragments (e.g., '{% include list-simple-valuesets.xhtml %}'), with the items on the page rendered in seemingly random order by the IG Publisher.  It would be be very helpful if these lists were instead ordered alphabetically by the title.  That would make the page much easier to read and navigate.

**Comment by rhausam** [comment]
It appears that this capability is already available, using the 'list-simple-name-' fragments, instead.  It might also be useful to have a 'list-simple-title-' version of the fragments, as the title is actually what is displayed.  In the meantime, a way to work around that is to make sure that the 'name' values have the same alphabetical ordering as the 'title' values.

**Comment by lmckenzi** [comment]
These are now being sorted alphabetically
