### ISSUE TITLE
ignoreWarnings.txt fails to suppress all messages

### ISSUE THREAD

**Issue by atruskot** [HL7/fhir-ig-publisher#470]
Documentation found [here](https://confluence.hl7.org/pages/viewpage.action?pageId=66938614#ImplementationGuideParameters-ManagingWarningsandHints) and [here](https://build.fhir.org/ig/FHIR/ig-guidance/using-templates.html#handling-errors-and-warnings) states that `ignoreWarnings.txt` can be used to suppress errors, warnings, and information messages that don't provide value to the IG. 

However, actually attempting to suppress errors does not appear to function as documented. For example, my IG is generating two types of errors, one because the publishing tool can't generate the OMB Race codes and another because the publisher has added validation beyond the `uri` regex for `identifier.system`.

```
# Examples with local namespace assigning authorities (ex: PID-3.4.1 "PatientId") instead of an absolute URI.
Identifier.system must be an absolute reference, not a local reference

# The publication tooling does not currently support generation of this Value Set expansion
Canonical URL 'http://hl7.org/fhir/us/core/ValueSet/omb-ethnicity-category' does not resolve

# Testing a warning
Unknown System specified, so Concepts and Filters can''t be checked
```

![image](https://user-images.githubusercontent.com/95640878/179229970-6e7b95e7-28a7-485f-b578-14c1aabb8538.png)

**Comment by grahamegrieve** [comment]
Errors cannot be suppressed. where in the documentation does its say they can?

**Comment by atruskot** [comment]
From the two documents I linked in the original post: 


> This file has the following format:
> == Suppressed Messages ==
> 
> \# Your Reason Here
> error or warning message to be suppressed


> Warnings and information messages, and some errors, can be silenced by including them in the input/ignoreWarnings.txt file. Example content for this file is shown below, and includes full messages copied from the qa.txt file, along with explanatory text in '#' prefixed comments. The lines in the file should be grouped so that an explanatory comment precedes a series of messages that are to be ignored.
> The content of the ignoreWarnings.txt file is included in the QA report to support review of the IG.
> == Suppressed Messages ==
> \# Errors to suppress
> \# This is a known IG Publisher error
> ERROR: /Users/skravitz/git/davinci-pdex-plan-net/fsh/build/output/searchform.html#/html/body/div/div/a/img/div/div/nav/div/div/ul/li/a at Line 64, column 21: The link 'history.html' for "History" cannot be resolved


Setting aside the discrepancies between documentation and behavior, I think the underlying issue is that the tooling's definition of error is not consistent. The errors that I show in my examples above should likely be considered as warnings rather than errors. They do not stop execution of the tooling but they are viewed as abnormal to be flow. One acceptable alternative approach to resolve this bug could be to review and correct all warnings that are currently being classified as errors.

Of course, even the documentation calls out the fact that users may wish to suppress error messages that result in defects in the tooling itself. It really seems that there was once an intention to suppress the errors that are being generated in `qa.html`. 

>The implementation guide publisher generates many Warnings and information messages. They may arise from:
> * Errors in the design of the Implementation Guide
> * Bugs in the publication tooling
> * Necessary outcomes from the specification (not an issue at all)

**Comment by atruskot** [comment]
It really does seem that there are a lot of false positive errors coming out of the publisher's validation. The false positives really make it difficult for teams to rely on this validation tool. 

As an example, today I experienced another terminology error while playing around with ICD codes. Example: [Z00.01](https://www.icd10data.com/ICD10CM/Codes/Z00-Z99/Z00-Z13/Z00-/Z00.01): 

> The code "Z00.01" is not valid in the system http://hl7.org/fhir/sid/icd-10; The code provided (http://hl7.org/fhir/sid/icd-10#Z00.01) is not valid in the value set 'All codes known to the system' (from http://tx.fhir.org/r4) for 'http://hl7.org/fhir/sid/icd-10#Z00.01'

Same type of errors pop up for US Core value sets. [example](http://hl7.org/fhir/us/core/ValueSet/omb-ethnicity-category)

> Canonical URL 'http://hl7.org/fhir/us/core/ValueSet/omb-ethnicity-category' does not resolve

**Comment by grahamegrieve** [comment]
Raise general issues here: https://chat.fhir.org/#narrow/stream/179252-IG-creation

**Comment by lmckenzi** [comment]
It's possible to suppress errors related to broken links.  Other errors cannot be suppressed.  To the best of our knowledge, the validator does not produce false positive errors.  If you find places where false positives are being produced, please submit them explicitly.
