### ISSUE TITLE
Generated Narrative Text in example json is displaying (R) mark (&reg) instead of #174 from a Code System entry.

### ISSUE THREAD

**Issue by ekivemark** [HL7/fhir-ig-publisher#474]
[FHIR-36176](https://jira.hl7.org/browse/FHIR-36176) identifies a Technical Correction:

The problem is that there's a "reg;" in the text and the narrative page says there should not be HTML entries.  This should be replaced with "#174;" 

This relates to an example: []ExplanationOfBenefit-PDexPriorAuth1(http://build.fhir.org/ig/HL7/davinci-epdx/ExplanationOfBenefit-PDexPriorAuth1.json.html) 

The item in the narrative is the description from the CPT Code System that incorporates the (R) mark.

(<a href=\"http://terminology.hl7.org/3.1.0/CodeSystem-CPT.html\">Current Procedural Terminology (CPT&reg;)</a>#99202)

**Comment by lmckenzi** [comment]
@ekivemark Is this now resolved?  We don't see the issue any longer...

**Comment by lmckenzi** [comment]
Closing
