### ISSUE TITLE
List-driven summary tables should show titles, not names

### ISSUE THREAD

**Issue by lmckenzi** [HL7/fhir-ig-publisher#480]
E.g. http://build.fhir.org/ig/HL7/UTG/identifiers.html.  The 'name' element isn't generally of interest to readers - it's only for code generation, and sometimes not even for that.  We should be exposing the titles.

**Comment by jessbota** [comment]
Do you have another update on this? We could try and get resources listed by title in the next THO release if this is resolved very soon.

**Comment by grahamegrieve** [comment]
I don't even know why they aren't, but I can't build THO to check right now. See question in Zulip

**Comment by grahamegrieve** [comment]
done next release
