### ISSUE TITLE
-publisher-update Throws exception when using -registry n/a

### ISSUE THREAD

**Issue by cames-be** [HL7/fhir-ig-publisher#482]
When using the `-publisher-update` command and the `-registry n/a` option (along with `no-registry=true` in the publisher.ini file), an exception is thrown due to a missing null reference check in two places.

https://github.com/HL7/fhir-ig-publisher/blob/master/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/Publisher.java#L10098

and

https://github.com/HL7/fhir-ig-publisher/blob/master/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/utils/IGWebSiteMaintainer.java#L120

Both of these locations call `reg.finish()` on a null object due to the initialization check for the "n/a" option `IGRegistryMaintainer reg = "n/a".equals(registry) ? null : new IGRegistryMaintainer(registry);`  The `reg` variable should be checked for null before calling `finish()`.

This lack of a check hurts the validation used on a build machine due to needing to catch/ignore exceptions thrown by the publisher and can lead to bad published IGs.

**Comment by lmckenzi** [comment]
@cames-be Is this still an issue?

**Comment by cames-be** [comment]
@lmckenzi Yes this is still an issue. I verified using version 1.6.18 and an exception is thrown here https://github.com/HL7/fhir-ig-publisher/blob/1.6.18/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/web/IGWebSiteMaintainer.java#L126

**Comment by grahamegrieve** [comment]
why are you using -publisher-update? it's been superseded by go-publish, and isn't really maintained anymore

**Comment by cames-be** [comment]
It's from when we first started publishing our IG and haven't changed it. We're currently upgrading the publisher version we're using so I'll look to switch over to go-publish.

**Comment by lmckenzi** [comment]
Closing as won't fix - use go-publish.  If there's an issue with that, then please re-raise.
