### ISSUE TITLE
Add possibility to include png as well as SVG graphics from PlantUML

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#483]
we could add a parameter to generate PNG or SVG, but it seems better to just generate them both and let the user pick the file they want.

The change could be duplicating this block, but with -tpng instead of -tsvg 
https://github.com/HL7/ig-template-base/blob/master/scripts/ant.xml#L99

Impact: This change is not expected to have any impact on IGs that don't use it: the publisher only takes up the files that are actually referenced in the IG, so the PNG files wwill be generated but will not be in the output.

**Comment by lmckenzi** [comment]
What's the purpose of supporting multiple formats?  Isn't SVG always better than PNG?

**Comment by lmckenzi** [comment]
Would still like an understanding of why PNGs would be necessary.  Note that SVGs are generated as includes and are actually incorporated into the HTML/markdown file where they're referenced (and so aren't generated to the output if not referenced).  However, with PNGs we couldn't use that approach and therefore PNGs would be in the output regardless of whether they were referenced.

**Comment by costateixeira** [comment]
in addition, SVGs have hyperlinks. PNGs don't, unless we generate the cmap
as well. my experience is that it is not so good to use them.

**Comment by lmckenzi** [comment]
@costateixeira So are you ok with us closing this - you had initiated the request

**Comment by costateixeira** [comment]
I don't recall where this came from, and obviously hasn't been a pressing need. Happy to drop this and if the need re-emerges will create another.
