### ISSUE TITLE
Add include / revInclude parameters to capability statement page

### ISSUE THREAD

**Issue by jkiddo** [HL7/fhir-ig-publisher#487]
As mentioned on https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/feature.20request/near/182026627 here's a request to add include/revInclude information to the capability statement page

**Comment by lmckenzi** [comment]
@vassilpeytchev - is this now supported?

**Comment by vassilpeytchev** [comment]
Yes, has been for a while
