### ISSUE TITLE
Unknown EncounterStatus code in R4B

### ISSUE THREAD

**Issue by rathpanyowat** [HL7/fhir-ig-publisher#490]
When I tried to build an IG in R4B (4.3.0) by including an example of Encounter instance. If the encounter status was set to some status such as "arrived" "triage" "finished", etc. , the IG will report this error: `Unknown EncounterStatus code '[status]'`.  Some status such as "planned" or "in-progress" seem to work fine.

This error message will not be shown if I switch the version of IG to R4 (4.0.1)

**Comment by lmckenzi** [comment]
@rathpanyowat - is this still an issue?

**Comment by rathpanyowat** [comment]
@lmckenzi I think it's not an issue anymore.
