### ISSUE TITLE
In R4B, Unknown.Unrecognised resource type 'MedicationStatement'

### ISSUE THREAD

**Issue by rathpanyowat** [HL7/fhir-ig-publisher#492]
In R4B, when I tried to create a MedicationStatement resource (any valid content, including the example in FHIR spec https://www.hl7.org/fhir/medicationstatementexample1.json), I'll get this error message: 

`Unable to convert resource MedicationStatement/example001 Unknown.Unrecognised resource type 'MedicationStatement' (in property 'resourceType')`

However, the IG seems to work fine despite this message. This problem doesn't exist if I switch the IG version to R4.

**Comment by atruskot** [comment]
For what it's worth, I'm getting a similar issue when building example `PaymentReconciliation` resources. Everything seems to work but I just get these errors during build. 

>Unable to convert resource PaymentReconciliation/example-payment-reconciliation Unknown resource PaymentReconciliation (01:27.505)

**Comment by lmckenzi** [comment]
Is this still a problem @rathpanyowat @atruskot

**Comment by rathpanyowat** [comment]
@lmckenzi  For me, I think it's not an issue anymore. I'm not sure about @atruskot

**Comment by lmckenzi** [comment]
Closed on the belief this is no longer an issue.  If there are still problems, please re-open.
