### ISSUE TITLE
In R4B, property patientInstruction is a class com.google.gson.JsonPrimitive looking for an Array 

### ISSUE THREAD

**Issue by rathpanyowat** [HL7/fhir-ig-publisher#493]
In FHIR spec, AllergyIntolerance.patientInstruction is a string. I created an AllergyIntolerance instance and tried to include it in the IG. If the IG version was set to R4 (4.0.1), everything seems to work fine. But if I switch to R4B (4.3.0), I'll get this error message: `Unable to convert resource Appointment/example property patientInstruction is a class com.google.gson.JsonPrimitive looking for an Array`.

However, the IG seem to work fine despite this error message when building it.

**Comment by lmckenzi** [comment]
Is this still occurring @rathpanyowat

**Comment by rathpanyowat** [comment]
@lmckenzi  I think it's not an issue anymore.
