### ISSUE TITLE
FHIR-CDA: "code" data type is broken

### ISSUE THREAD

**Issue by seanmcilvenna** [HL7/fhir-ig-publisher#5]
https://build.fhir.org/ig/HL7/fhir-cda/StructureDefinition-Guardian.html

The "classCode" is a data type "code". When clicking on "code", the link sends the user to the core FHIR data type for "code". This is not actually a "FHIR" data type, it is a CDA data type that should have a separate page. Not sure what to do about it. Not sure if it's an IG Publisher bug or not, either.

**Comment by grahamegrieve** [comment]
it is a FHIR code data type
