### ISSUE TITLE
XML display of examples is difficult to read near the text element

### ISSUE THREAD

**Issue by RichardTON** [HL7/fhir-ig-publisher#502]
In http://build.fhir.org/observationdefinition-example.xml.html generated on Thu, Sep 15, 2022 10:15+0000. the text element does not line wrap and the category element is lost off page
![image](https://user-images.githubusercontent.com/31459746/191138715-7bee330f-616a-4de1-90c1-c5f19291070b.png)

In https://hl7.org/fhir/5.0.0-snapshot1/observationdefinition-example.xml.html the text element is wrapped, but the category element is mislocated.

![image](https://user-images.githubusercontent.com/31459746/191138892-dee23e54-3baa-4013-95fd-952c46d89f69.png)

**Comment by grahamegrieve** [comment]
These examples were not produced by the IG publisher

**Comment by RichardTON** [comment]
Strange.
That makes it an issue with the IG and our reviewing of hand-built examples.

**Comment by RichardTON** [comment]
Jira issue raised on ObservationDefinition: https://jira.hl7.org/browse/FHIR-39042
