### ISSUE TITLE
IG Publisher hangs on Windows when no menu.xml is provided

### ISSUE THREAD

**Issue by cmoesel** [HL7/fhir-ig-publisher#532]
If no `menu.xml` is included (i.e., no `menu` in `sush-config.yaml` and no `input/includes/menu.xml` file), then the IG Publisher hangs during the Jekyll generation process.  This appears to be Windows specific, as this causes my Mac to crash, but @markkramerus's Windows PC just hangs after `Jekyll: Generating...`:

IG Publisher: 1.2.8
Template: fhir.base.template#current
FHIRVersion: 4.0.1

```
onGenerate.plantUml:
onGenerate.copyDataFiles:
onGenerate.extend:
onGenerate:
Template Done                                                                    (01:04.858)
Generating Summary Outputs                                                       (01:33.903)
Sending Usage Stats to Server                                                    (01:53.854)
## Memory (MB): Use = 1207, Free = 1118, Total = 2326, Max =4044
Reclaiming memory...
## Memory (MB): Use = 356, Free = 851, Total = 1208, Max =4044
Run jekyll: jekyll build --destination "C:\Users\mkramer\GitHub\fhir-north-2022\fsh-ig\output" (in folder C:\Users\mkramer\GitHub\fhir-north-2022\fsh-ig\temp\pages) (01:54.257)
Jekyll: Source: C:/Users/mkramer/GitHub/fhir-north-2022/fsh-ig/temp/pages        (02:06.140)
Jekyll: Generating...                                                            (02:06.143)
# hangs here
```

**Comment by lmckenzi** [comment]
If Jekyll runs into a problem, it *always* hangs on Windows.  To see the error, you need to run Jekyll manually.  Not sure if there's much we can do about this.

**Comment by cmoesel** [comment]
Oh, that's unfortunate.

I don't know how much we want to special case things, but since a `menu.xml` is generally _required_ for all IGs, and since it's easy to mistakenly leave it out, can IGP check for its existence (and error out if not found) before running Jekyll?

**Comment by costateixeira** [comment]
can this be avoided by having a minimal menu.xml in the template includes?

**Comment by lmckenzi** [comment]
The template could possibly check for the existence of the file and fail early.  Feel free to submit a ticket against the template.  Not a fan of generating a default menu as that discourages people from thinking about what should actually be in it.  (Unless the default has a menu items that say "Please" "Define" "Menu" :>)

**Comment by grahamegrieve** [comment]
it's definitely a template issue. if the template requires the file, it should check that it exists

**Comment by cmoesel** [comment]
@lmckenzi -- I'm glad to file an issue against the template.  Is [fhir.base.template](https://github.com/HL7/ig-template-base) the right template to file the issue on?

**Comment by lmckenzi** [comment]
Yes

**Comment by cmoesel** [comment]
I'm closing this issue since I've filed one against the template here: https://github.com/HL7/ig-template-base/issues/203
