### ISSUE TITLE
Problem with markdown hyperlinks in code systems

### ISSUE THREAD

**Issue by lmckenzi** [HL7/fhir-ig-publisher#540]
When a code in a code system includes markdown in its definition with a relative hyperlink, when that code is referenced in a value set defined in a different IG, the hyperlink is broken because the relative hyperlink isn't made absolute.  See http://build.fhir.org/ig/HL7/fhir-sdoh-clinicalcare/ValueSet-SDOHCC-ValueSetObservationStatus.html#l592 for an example.

As a side note, the markdown in the CLD part of the value set rendering isn't rendering the hyperlink at all.

See also: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Link.20'provenance.2Ehtml'.20for.20.22Provenance.22.20cannot.20be.20resolved

**Comment by grahamegrieve** [comment]
Fixed next release
