### ISSUE TITLE
Version check in QA page malprints the latest version

### ISSUE THREAD

**Issue by vadi2** [HL7/fhir-ig-publisher#550]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/110988/200516490-199ff9c2-f05f-4fc4-9323-6c98ba08ba7f.png">

The message is correct that the publisher is outdated, but as of writing this the latest version is `1.2.13` and not `v?pub-ver-1? `

**Comment by lmckenzi** [comment]
This is now fixed.
