### ISSUE TITLE
Rendering issues in StructureDefinition detailed descriptions

### ISSUE THREAD

**Issue by qligier** [HL7/fhir-ig-publisher#560]
For StructureDefinitions, in the tab **Detailed descriptions**, there are rendering issues with references.

In the **Differential Elements Table** and **Key Elements Table**, there are two closing parenthesis:
![2022-11-23 13 19 08  8c46316d41d8](https://user-images.githubusercontent.com/3299399/203545620-13b1d375-e1f1-4562-bb1c-15342a2112c8.png)

In the **Snapshot Elements Table**, there are also two closing parenthesis, but separators are also missing between types (it becomes hard to read):
![2022-11-23 13 22 32  0782c1fdbbb7](https://user-images.githubusercontent.com/3299399/203546075-a139714e-b9e4-4b22-881c-c9edd126441e.png)

The two closing parenthesis are caused by [StructureDefinitionRenderer.java#L1617 and L1635](https://github.com/HL7/fhir-ig-publisher/blob/master/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java#L1617).
I guess the separator should be added in the loop at [StructureDefinitionRenderer.java#L1928](https://github.com/HL7/fhir-ig-publisher/blob/master/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/renderers/StructureDefinitionRenderer.java#L1928).

**Comment by grahamegrieve** [comment]
how to reproduce?

**Comment by qligier** [comment]
With the last IG Publisher, any resource with an element of type "Reference" should reproduce the bug:
```fsh
Profile: MedicationStatementTest
Parent: MedicationStatement

// Produce a differential
* informationSource only Reference(Patient | Practitioner)
```

**Comment by qligier** [comment]
Also visible here for example: https://build.fhir.org/ig/CARA-ch/ch-emed-epr/StructureDefinition-ch-emed-epr-medicationstatement-treatmentplan-definitions.html

(From source https://github.com/CARA-ch/ch-emed-epr/blob/master/input/fsh/structuredefinition/medication_statement_mtp.fsh)

**Comment by grahamegrieve** [comment]
ok. fixed next commit/release

**Comment by qligier** [comment]
Thank you!
