### ISSUE TITLE
Wrong expansion of links to FHIR documentation 

### ISSUE THREAD

**Issue by markkramerus** [HL7/fhir-ig-publisher#57]
Getting errors like `The link 'http://hl7.org/fhir/R4/StructureDefinition-CancerStageParent.html/extension-observation-focuscode.html' for "focusCode" cannot be resolved`.

This is indicative of markdown links in the StructureDefinitions, which appear in comments and descriptions as `[focusCode](extension-observation-focuscode.html).` are not getting the correct expansion. 

How does the IG Pub know which links should be relative to the IG base, and which should expanded as links to FHIR documentation?

**Comment by grahamegrieve** [comment]
how to reproduce this?

**Comment by grahamegrieve** [comment]
@markkramerus when a derivative snapshot is generated, the links are made absolute. This problem is usually indicative of an error in the underlying spec package, but where would I look to reproduce this?

**Comment by lmckenzi** [comment]
No response from commenter in 2 years.  Closing.  (Lots of work has happened in this area, so hopefully no longer an issue.  If there's still a problem, re-raise with a specific place the issue can be seen.)
