### ISSUE TITLE
Hide artifacts from output and pages

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#599]
Is it possible that some artifacts would be considered but not displayed in the artifact index and ToC?

Example: When adding logical models, we may need to create custom logical data types. But those end up cluttering the Artifacts and TOC. 
Can we tell the template / publisher "do not show this"

**Comment by lmckenzi** [comment]
Discussed and decided that the complexity isn't worth it.  Section numbers are driven off ToC.  May be some possible solutions coming out of the Composition-based ToC/Artifacts List approach once we get to it.
Short terms solution - put the artifacts you don't want in your publication in a different IG and reference it.
