### ISSUE TITLE
Support for non-english language

### ISSUE THREAD

**Issue by peturv** [HL7/fhir-ig-publisher#62]
I've been working with an IG where a requirement is delivery in a non-english language.
One of the localisation issues is text snippets generated by the publisher tool.

Am submitting the code I have been using to handle language localisation in the publisher so far, hoping it will be of use.

**Comment by lmckenzi** [comment]
Will leave #63 active.  The general question of how translations will be handled will be dealt with as part of the WHO-funded project over the coming year.
