### ISSUE TITLE
IG Publisher fails to run in `git worktree` folder

### ISSUE THREAD

**Issue by masnick** [HL7/fhir-ig-publisher#634]
The IG publisher should support [git worktree](https://git-scm.com/docs/git-worktree), but appears to not currently. (This is a very useful `git` feature that allows you to check out multiple branches of a repo at the same time without having to clone multiple copies.)

## Steps to reproduce:

1. Assume `~/projects/some-ig` with branches `master` and `STU1-branch`
2. `cd ~/projects/some-ig && git checkout master`
3. `git worktree ~/projects/some-ig-STU1 STU1-branch`
4. `cd ~/projects/some-ig-STU1` and run the IG publisher

The publisher will nearly complete, but will fail with:

```
Publishing Content Failed: /Users/you/projects/some-ig-STU1/.git/HEAD (Not a directory) (08:48.065)
                                                                                 (08:48.065)
Use -? to get command line help                                                  (08:48.065)
                                                                                 (08:48.066)
Stack Dump (for debugging):                                                      (08:48.066)
java.io.FileNotFoundException: /Users/you/projects/some-ig-STU1/.git/HEAD (Not a directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.hl7.fhir.utilities.TextFile.fileToString(TextFile.java:148)
	at org.hl7.fhir.igtools.publisher.Publisher.getGitStatus(Publisher.java:8584)
	at org.hl7.fhir.igtools.publisher.Publisher.generateDataFile(Publisher.java:8521)
	at org.hl7.fhir.igtools.publisher.Publisher.generateSummaryOutputs(Publisher.java:7394)
	at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:6498)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:1087)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:905)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10981)
```

## Note

For a folder created by `git worktree`, there is no `.git` folder. Instead, there is a `.git` _file_ with the following contents:

```
gitdir: /Users/you/projects/some-ig/.git/worktrees/some-ig-STU1
```

Temporarily removing the `.git` file allows publisher.jar to run successfully (but breaks git in the worktree until it's replaced).

**Comment by grahamegrieve** [comment]
@dotasek well, that git hack doesn't work anymore. This is trying to work out the branch - not sure what the templates do with it. @lmckenzi do you know?

**Comment by masnick** [comment]
If it's not possible to run `Runtime.getRuntime().exec( "git rev-parse --abbrev-ref HEAD" );` to use git plumbing to get the branch name, it looks like you can add a special case by reading the value of `gitdir` from the `.git` file, and then reading the contents of `HEAD` from that folder (`ref: refs/heads/STU1-branch` in this case).

**Comment by grahamegrieve** [comment]
I had trouble with inconsistent output from ```git rev-parse --abbrev-ref HEAD``` before, but now I can't recreate whatever that problem was. So perhaps that's the answer

**Comment by dotasek** [comment]
I've been working with this today, and I can definitely see inconsistent output from `git rev-parse --abbrev-ref HEAD`.

If I run directly from within my command-line, it seems to always get the correct branch, but there are odd cases where it always returns `HEAD` when run from Java, regardless of what branch it's on. There's some stackoverflow indicating that this could be related to checking out commits instead of actual branches, but that wouldn't explain different results.

**Comment by masnick** [comment]
@dotasek [this](https://stackoverflow.com/questions/6245570/how-do-i-get-the-current-branch-name-in-git) indicates `git symbolic-ref --short HEAD` may somehow be more robust (I don't pretend to understand why).

Since ~2019, git has also supported `git branch --show-current`.

**Comment by dotasek** [comment]
Thanks @masnick, I'll swap out both in my tests and see what happens.

**Comment by dotasek** [comment]
`git symbolic-ref --short HEAD` doesn't appear to do it. It returns an empty string in the same cases HEAD did.

`git branch --show-current` seems to be working, though. Test cases appear correct, just testing with an actual IG now in case that makes a difference.

**Comment by lmckenzi** [comment]
Believe this is now fixed.
