### ISSUE TITLE
IG Publisher Version >= 1.2.47

### ISSUE THREAD

**Issue by noctiz89** [HL7/fhir-ig-publisher#641]
Hello,

I get the following Error with new Publisher versions:

`FHIR IG Publisher Version 1.2.47 (Git# 47de7e96d18f). Built 2023-03-14T21:40:55.24Z (23 hours old)
Detected Java version: 19.0.2 from C:\Program Files\Java\jdk-19 on Windows 10/amd64 (64bit). 4092MB available
dir = D:\CDE-Katalog, path = C:\Program Files\Java\jdk-19\bin\javaw.exe;D:\Programme\Ruby32-x64\bin;C:\Program Files\Java\jdk-19\\bin;C:\Program Files\Java\jdk-

[...]

Parameters: -ig .
Start Clock @ Mittwoch, 15. M├ñrz 2023 um 22:09:01 Mitteleurop├ñische Normalzeit (2023-03-15T22:09:01+01:00)

API keys loaded from C:\Users\noctiz\fhir-api-keys.ini                           (00:00.016)
Package Cache: C:\Users\noctiz\.fhir\packages                                    (00:00.023)
Publishing Content Failed: First entry cannot be root: D:\                       (00:00.030)
                                                                                 (00:00.032)
Use -? to get command line help                                                  (00:00.034)
                                                                                 (00:00.035)
Stack Dump (for debugging):                                                      (00:00.036)
java.lang.RuntimeException: First entry cannot be root: D:\
        at org.hl7.fhir.igtools.publisher.Publisher.runFsh(Publisher.java:2334)
        at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:899)
        at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:10981)
Drücken Sie eine beliebige Taste . . .`

Currently version 1.2.39 works fine for me. 

Good luck. :)

**Comment by lmckenzi** [comment]
@noctiz89 is this still an issue with the most recent version of the publisher?

**Comment by lmckenzi** [comment]
Poke.

**Comment by lmckenzi** [comment]
Based on no response, we assume this is now fixed.  If the problem still persists, please re-submit and provide a link to a Git project we can test with.
