### ISSUE TITLE
Describe API between IG Publisher and terminology server(s)

### ISSUE THREAD

**Issue by bdc-ehealth** [HL7/fhir-ig-publisher#642]
see: https://chat.fhir.org/#narrow/stream/179202-terminology/topic/Terminology.20server.20requirements.20for.20IG.20builds.2E.2E.2E

**Comment by lawley** [comment]
See also https://chat.fhir.org/#narrow/stream/179202-terminology/topic/Change.20to.20validator.20use.20of.20terminology.20server for the introduction

**Comment by lmckenzi** [comment]
This isn't a change to the publisher itself, so not appropriate here.  However, the documentation is in progress.  The Zulip stream mentioned by Michael above is the best place to follow.
