### ISSUE TITLE
In the tree, display the name of the profile instead of the base resource

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#701]
In a profile elements tree display, the name of the top element should(?) be the be the name of the profile, not the name of the base resource.

![image](https://github.com/HL7/fhir-ig-publisher/assets/16153168/5d4fdfd6-068d-4e9f-a3f9-ba88baab3901)

**Comment by lmckenzi** [comment]
The root of the hierarchy has *always* been the name that shows up in the instance and we don't think this should change.  The StructureDefinition.name, title and other profile metadata appears at the top of the profile page, not in the table views.

No change
