### ISSUE TITLE
Publisher is not exposing Title for TestScript artifacts in the _data files and fragments

### ISSUE THREAD

**Issue by lmckenzi** [HL7/fhir-ig-publisher#709]
E.g. http://wildfhir4.aegis.net/ig/dev-satisfaction-r4/0.3.0/TestScript-DEVSATObservationdynamicreadvalidatejson.html the title should be "HL7 FHIR R4 TestScript Read Validate DEVSAT-Observation" as it is in the XML & JSON, not "testscript-DEVSAT-Observation-dynamic-read-validate-json"

Also http://wildfhir4.aegis.net/ig/dev-satisfaction-r4/0.3.0/StructureDefinition-dev-satisfaction-observation-testing.html the test scripts list should be using the titles

**Comment by rettema** [comment]
Additional information - while researching and testing in my local environment, I found that the SUSHI generated TestPlan and TestScript resources are affected. Predefined TestPlan and TestScript resource instance title values are correctly processed. This appears to be SUSHI issue when generating the ImplementationGuide resource definition.resource.name values from the SUSHI generated TestPlan and TestScript resource instances.

The fhir-ig-publisher logic populates the page title values from the ImplementationGuide.definition.resource.name values.

**Comment by rettema** [comment]
New sushi issue submitted to correct this - https://github.com/FHIR/sushi/issues/1296
