### ISSUE TITLE
Displaying base-64 encoded content is not useful

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#719]
DocumentReference narrative  shows hash but it's not useful and it ends up taking a lot of space.
Should be replaced by an indication of the size.

Per discussion here:
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Attachement.2EData.20displays.20entire.20file.20contents.20in.20narrative

**Comment by lmckenzi** [comment]
Ideally we'd like the actual image/PDF/etc., but that's more work, so go with size for now.

**Comment by lmckenzi** [comment]
Grahame has made the change.  Will be in next release
