### ISSUE TITLE
Fix the page content generator to work with both markdown and html

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#723]
Fix the page content generator to work with both markdown and HTML

The problem is outlined in Zulip here:  https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/How.20is.20the.20markdown-toc.20generated.3F

proposal is to modify the liquid to look for either `### ` or `<h3>` tags.  Unless we are using the[ built-in kramdown feature](https://kramdown.gettalong.org/converter/html.html#toc), then will have to dig deeper to see if this is possible.

**Comment by lmckenzi** [comment]
We're using the built-in kramdown feature for markdown.  We have XSLT for the XHTML.  It's not really straightforward to do XSLT on markdown.

**Comment by Healthedata1** [comment]
OK then I  will have to review how it works and when the markdown gets rendered to HTML.  ... or ...  inform folks that they need to use markdown headers when using markdown pages for it to work.

**Comment by lmckenzi** [comment]
It's our belief that we should simply say "don't put <h?/> tags in a page that's declared as markdown".  If you really need tight control over your headings in a way that markdown doesn't allow for, then write your whole page as XHTML.  This can be re-opened if there's a concrete plan for how to easily handle mixing and matching.
