### ISSUE TITLE
USCDI Label in FHIR US Core

### ISSUE THREAD

**Issue by hbuitendijk** [HL7/fhir-ig-publisher#725]
A label was added to the FHIR US Code dif/snapshot/etc. tables' short descriptions.  However, that label "disappears" when viewing the detailed definitions.  Suggest that this label can be visible in all views of the profiles' short description displays.

**Comment by lmckenzi** [comment]
Do you mean that you want the short descriptions to appear in the data dictionary views?  If not, can you provide a screenshot or two to explain what you're looking for?

**Comment by hbuitendijk** [comment]
Correct, so that when you see the USCDI label in the various table views, it is also available in the list of attribute definitions for continuity.

Hans J. Buitendijk, M.Sc., FHL7
Director, Interoperability Strategy - Oracle Health
+1 (610) 210 2087
***@***.***
________________________________
From: Lloyd McKenzie ***@***.***>
Sent: Tuesday, August 1, 2023 5:16:41 PM
To: HL7/fhir-ig-publisher ***@***.***>
Cc: Hans Buitendijk ***@***.***>; Author ***@***.***>
Subject: [External] : Re: [HL7/fhir-ig-publisher] USCDI Label in FHIR US Core (Issue #725)


Do you mean that you want the short descriptions to appear in the data dictionary views? If not, can you provide a screenshot or two to explain what you're looking for?

**Comment by lmckenzi** [comment]
The opinion of those on the tooling call is that the information in the short definition is expected to always be redundant with information that already appears in the detailed page (either the definition or the vocabulary binding), so adding the short description to the page would be unnecessary noise.  If the USCDI flag is considered to be important to be seen on both pages, then it should perhaps be added into the comment or some other element that shows up on the detailed page as well.
