### ISSUE TITLE
New feature request:  Produce a table of all the ValueSets and CodeSystems used by the IG

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#734]
New feature request:  Produce a table of all the ValueSets and CodeSystems used by the IG.  I propose  both CSV, Excel files, and rendered tables available with the following columns:

For the CSV, and Excel files:

URL
version
status
oid(s)
name
title
description
code systems referenced
Profile(s) where it is used
source ( IG|FHIR|THO|VSAC|Other?(e.g., PHINVADs))

For the rendered tables:

row #
title (linked to URL)
Profile(s) where it is used
source (IG|FHIR|THO|VSAC|Other?(e.g., PHINVADs))

The  "Table for VS US Core IG" sheet illustrates an early design for the rendered output for US Core.

[US Core C-CDA Value Set Compare.xlsx](https://github.com/HL7/fhir-ig-publisher/files/12318613/US.Core.C-CDA.Value.Set.Compare.xlsx)

We created a list for US Core CodeSystems here:  http://hl7.org/fhir/us/core/terminology.html#code-system-uris-used-in-us-core but having a single table with CodeSystem names linked to the URL (if available) would be ideal.

**Comment by lmckenzi** [comment]
What constitutes 'used'?  Bound in a mustSupport element?  Does the binding strength matter?  Do we care about value sets referenced within a value set?

**Comment by Healthedata1** [comment]
>
> What constitutes 'used'? Bound in a mustSupport element?


In a differential


Does the binding strength matter?

No

Do we care about value sets referenced within a value set?

yes,


Eric

Eric M Haas, DVM, MS
Health eData Inc
211 S Jefferson St, Napa, CA 94559
707.227.2608
***@***.***

**Comment by lmckenzi** [comment]
Would like to see this discussed more on Zulip to get a sense of what the wider community wants.  E.g. is there utility also in 'key elements' references or even snapshot references?  What about cross-referencing extension use?  Profile use?  Would people want XML or JSON, which could allow for a more hierarchical (and smaller) structure?

@Healthedata1, can you start a discussion?

**Comment by Healthedata1** [comment]
OK

Eric M Haas, DVM, MS
Health eData Inc
211 S Jefferson St, Napa, CA 94559
707.227.2608
***@***.***

**Comment by lmckenzi** [comment]
We're going to produce a registry of value sets and code systems, but those won't include dependencies (or references to them).  However, we will produce Excel and CSV files that list all artifacts from the IG as well as all of their dependencies and we will work to include a column that indicates whether the artifact is needed to satisfy a differential change, needed for key elements, or needed for snapshots (to allow the user to filter on which ones they want).

**Comment by grahamegrieve** [comment]
Done
