### ISSUE TITLE
Creation of cross paradigm IGs does not link to the correct 'Propose a change' URL in HL7 JIRA

### ISSUE THREAD

**Issue by reubendaniels** [HL7/fhir-ig-publisher#763]
The 'Propose a change' link (at the bottom) in cross paradigm IGs links to the FHIR issues link (http://hl7.org/fhir-issues) instead of the JIRA link for cross paradigm specifications (https://jira.hl7.org/projects/OTHER/issues/). For example, the 'Propose a change' link in the Gender Harmony IG: [](https://build.fhir.org/ig/HL7/fhir-gender-harmony/branches/main/#bottom).

**Comment by lmckenzi** [comment]
It's actually an issue with the template, not the publisher.  Specifically, there isn't a template for 'other' igs yet, so I guess people are using the FHIR one.  There's no template for v2 either.

**Comment by lmckenzi** [comment]
@lmckenzi will create an initial template.  @reubendaniels will chat w/ Dan about what the logo and color-scheme ought to be.
