### ISSUE TITLE
Issue Rendering Abstract Profiles

### ISSUE THREAD

**Issue by saulakravitz** [HL7/fhir-ig-publisher#765]
When an abstract profile (e.g., [this one](http://build.fhir.org/ig/HL7/fhir-mCODE-ig/StructureDefinition-mcode-cancer-stage.html)) is rendered, there is an issue rendering the child profiles. Instead of the profile names, their FHIR Type is rendered. The hyperlinks are correct.
This is perplexing to the reader. I figure this may be a feature (intentional to save space) rather than a bug, but figured I'd report it in case it is unintentional.
![image](https://github.com/HL7/fhir-ig-publisher/assets/37216915/23068a1f-068f-4099-82e5-f5659f54bb38)

**Comment by lmckenzi** [comment]
Fixed
