### ISSUE TITLE
Additionally render contact in {{[type]}}-{{[id]}}-summary.xhtml

### ISSUE THREAD

**Issue by Nik-xT** [HL7/fhir-ig-publisher#769]
Initial zulip discussion: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Showing.20Contact.20in.20Terminologies 

Right now there is some rendering of metadata done in {{[type]}}-{{[id]}}-summary.xhtml, that looks something like that: 
![image](https://chat.fhir.org/user_uploads/10155/HndIdJZrn3Xsea_n93J_briq/image.png)

It would be a good feature for the Austrian eHealth community, to render the contact in that table, maybe turning it on and off in the parameters (http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html). 
Knowing, that contact itself is a complex datatype (https://www.hl7.org/fhir/metadatatypes.html#ContactDetail), the actual solution is worthy of discussion.

**Comment by grahamegrieve** [comment]
I don't know why you aren't seeing publisher. What fragment are you including?

**Comment by Nik-xT** [comment]
We do not mean the publisher (http://hl7.org/fhir/R4B/codesystem-definitions.html#CodeSystem.publisher, that in our case would not be clear if its maybe always ELGA GmbH, because we are handling the different inputs from the experts/developers, but the Expert-Organisations do stand in the contact)
it's the contact (http://hl7.org/fhir/R4B/codesystem-definitions.html#CodeSystem.contact) that can't be redered. 

Just added the publisher, see https://elga-gmbh.gitlab.io/termgit-dev/CodeSystem-appc-anatomie.html and it origin fhir file https://gitlab.com/elga-gmbh/termgit-dev/-/raw/3dd770d0c9829e3d2d46c4062faaa109d149dcc4/terminologies/CodeSystem-appc-anatomie/CodeSystem-appc-anatomie.4.fhir.xml

Not sure what you mean with fragment, isn't it the {{[type]}}-{{[id]}}-summary.xhtml? See following line in our template https://gitlab.com/elga-gmbh/terminologit-template/-/blob/master/layouts/layout-codesystem.html?ref_type=heads#L19

**Comment by grahamegrieve** [comment]
Looks like you need to try with the new IG publisher and turn on the
publisher row in your config.json


——
FHIR Product Director at HL7; Adjunct Science Fellow, CSIRO
http://www.healthintersections.com.au / ***@***.*** /
+61 411 867 065
Benson & Grieve:   Principles of Health Interoperability (Health
Information Technology Standards), 4th ed -
http://www.springer.com/978-3-030-56882-5

**Comment by Nik-xT** [comment]
Oh, I see what happend here. The IG publisher is rendering the contact element only if the publisher element is given. Contact alone, without a publisher will be ignored. With that knowledge, thx for your patience and next time I will read the resource elements definitions more carefully.
