### ISSUE TITLE
Spurious(?) warnings about SNOMED Codes that Lack Semantic Tags

### ISSUE THREAD

**Issue by saulakravitz** [HL7/fhir-ig-publisher#771]
Per FMG review of mCODE STU3.0.0 IG.  Lloyd requested a bug report on this.
These warnings are reported:  
INFORMATION: ValueSet/mcode-cancer-stage-type-vs: ValueSet.compose.include[0]: This SNOMED-CT based include has some concepts with semantic tags (FSN terms) and some without (preferred terms) - check that this is what is intended
INFORMATION: ValueSet/mcode-radiotherapy-treatment-location-vs: ValueSet.compose.include[0]: This SNOMED-CT based include has some concepts with semantic tags (FSN terms) and some without (preferred terms) - check that this is what is intended

As far as we can tell, this is spurious.   Even it were accurate, not sure what we could do about them since it is an intensional include of a collection of codes.

**Comment by lmckenzi** [comment]
Same as https://github.com/HL7/fhir-ig-publisher/issues/773
