### ISSUE TITLE
Spurious dom-6 warning

### ISSUE THREAD

**Issue by markkramerus** [HL7/fhir-ig-publisher#772]
Received the following warning on mcode IG STU 3:
```
WARNING: DiagnosticReport/gx-genomics-report-adam-anyperson: DiagnosticReport: Rule dom-6: 'A resource should have narrative for robust management' Failed (defined in http://hl7.org/fhir/StructureDefinition/DomainResource) (Best Practice Recommendation)
```
However, the instance gx-genomics-report-adam-anyperson does have a `text.div` so it is not clear why IG Publisher reports this warning.

Publisher version 1.4.6.

**Comment by grahamegrieve** [comment]
fixed next release - actually a pretty deep internal issue that should've popped up long ago
