### ISSUE TITLE
Spurious information message

### ISSUE THREAD

**Issue by markkramerus** [HL7/fhir-ig-publisher#773]
mCODE STU 3 IG:
```
INFORMATION: ValueSet/mcode-cancer-stage-type-vs: ValueSet.compose.include[0]: This SNOMED-CT based include has some concepts with semantic tags (FSN terms) and some without (preferred terms) - check that this is what is intended
```
However, every value in the value set [mcode-cancer-stage-type-vs](http://build.fhir.org/ig/HL7/fhir-mCODE-ig/branches/master/ValueSet-mcode-cancer-stage-type-vs.html) has a semantic tag. 

I suspect the IG Publisher is looking for the first set of parentheses, and possibly this term triggers the error:
```
399566009 | Tumor-node-metastasis (TNM) category (observable entity)
```

**Comment by grahamegrieve** [comment]
Fixed next release (and yes, it was the double parentheses)
