### ISSUE TITLE
Get rid of spreadsheet error in IG QA

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#79]
When using spreadsheets with the IGPublisher, it currently produces the following two errors:
* The extension http://hl7.org/fhir/StructureDefinition/igpublisher-spreadsheet is unknown, and not allowed here
* URL value 'http://hl7.org/fhir/StructureDefinition/igpublisher-spreadsheet' does not resolve
Both should be suppressed

**Comment by lmckenzi** [comment]
These are no longer problems.
