### ISSUE TITLE
Add new view for "modified from base"

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#80]
Create a new fragment that provides a table view that includes all elements where something has been modified from the base resource. 
This will cause all extensions (including optional ones), elements that are optional but have additional usage notes or tweaks to their definitions, etc. to all show up.  Also show all parents of elements that are shown even if un-changed.

**Comment by costateixeira** [comment]
Should this be a direct comparison from base resource or the differentials in the entire stack?
For example if we have IHE profile -> IHE Domain profile ->National profile -> Product profile.. and if one of them makes patient.gender mandatory, it is interesting to see the total stacked changes but also being able to see where that specific change comes from.

**Comment by lmckenzi** [comment]
At some point, the view gets complex enough, you're better off walking up the stack and looking at what's happened to the element at each stage

**Comment by lmckenzi** [comment]
We will create a fragment that shows the ancestor hierarchy of a particular profile that provides a link to each ancestor and what IG it comes from.  Will add this to the profile, extension, and logical model layouts above the 'table' for the model.

**Comment by costateixeira** [comment]
@lmckenzi is this addressed with the new views?

**Comment by lmckenzi** [comment]
I think so?  Technically we only show stuff that's modified that meets the "key elements" criteria - but I think that's all that really matters?

**Comment by costateixeira** [comment]
suggest closing this issue then, given that you were the original requester and we seem to have what we need).
