### ISSUE TITLE
Operation to upload an IG?

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#800]
What would be the "standard" way of uploading a package to a running server?
Proposal: 
POST to `[server]/ImplementationGuide/$install`, with the payload

```json
{
  "resourceType": "Parameters",
  "parameter": [
    {
      "name": "npmContent",
      "valueBase64Binary": "[BASE64_ENCODED_NPM_PACKAGE_DATA]"
    }
  ]
}
```

**Comment by grahamegrieve** [comment]
I think this is firstly a jira issue for the spec itself. Once that's defined, it might become a IG publisher issue?

**Comment by costateixeira** [comment]
ok I was not sure where. Will create it there, leaving this open pending the Jira.

**Comment by costateixeira** [comment]
https://jira.hl7.org/browse/FHIR-43038

**Comment by lmckenzi** [comment]
This is not an IG publisher issue, so closing
