### ISSUE TITLE
Excel profile spreadsheets missing header row

### ISSUE THREAD

**Issue by Healthedata1** [HL7/fhir-ig-publisher#803]
The Excel profile spreadsheets available and generated by the publisher need to include the header row. See StructureDefinition-us-core-encounter.xlsx as an example:

https://build.fhir.org/ig/HL7/US-Core/downloads.html#consolidated-csv-and-excel-file-representations-of-profiles

The issue appears to have been introduced in 6.1.0... They look okay in version 6.0.0
The CSV files are unaffected.

**Comment by lmckenzi** [comment]
Fixed
