### ISSUE TITLE
Guide people to use 'element' rather than FHIRPath when their extension contexts are elements

### ISSUE THREAD

**Issue by lmckenzi** [HL7/fhir-ig-publisher#819]
We found a whole bunch of extensions defined with a context type of 'FHIRPath' where it turns out that the context expressions were simple elements.  This means that these extensions won't show up correctly in the cross-reference lists and may create confusion for systems that don't support FHIRPath-based extension contexts.

We should check the contexts for expressions and if they are in fact simple element paths, we should at least spit out a warning that says "The context expression seems to be a simple element path rather than a FHIRPath.  The context type should likely be 'element'."

**Comment by grahamegrieve** [comment]
This is done now
