### ISSUE TITLE
Add new view for "mustSupport + modifiers"

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#82]
Create a new fragment that provides a table view that includes all elements which are either mustSupport or that are marked as being a modifier.  Also display any parents of such elements

**Comment by grahamegrieve** [comment]
Presumably this is snapshot?

**Comment by lmckenzi** [comment]
It would be a filtered view of snapshot - only showing what's mustSupport or modifier

**Comment by lmckenzi** [comment]
Suggest closing in favor of #320

**Comment by lmckenzi** [comment]
Dealt with as part of #320
