### ISSUE TITLE
Binary Adjunct CQL Not Including JSON ELM Content 

### ISSUE THREAD

**Issue by c-schuler** [HL7/fhir-ig-publisher#822]
When the cql-options.json specifies JSON format, the JSON ELM content is not included in the generated Library.

The issue stems from this line: https://github.com/HL7/fhir-ig-publisher/blob/master/org.hl7.fhir.publisher.core/src/main/java/org/hl7/fhir/igtools/publisher/CqlSubSystem.java#L473

The fix is simple: change `CqlTranslator.Format.JSON` to `CqlTranslatorOptions.Format.JSON`

PR pending

**Comment by grahamegrieve** [comment]
fixed next release
