### ISSUE TITLE
Questionnaire.item.initial.valueReference expects Coding type

### ISSUE THREAD

**Issue by taylorkle** [HL7/fhir-ig-publisher#828]
I am using a questionnaire resource with  item.initial.valueReference 
```{
  "resourceType": "Questionnaire",
  "id": "Questionnaire1",
  "item": [
    {
      "initial": [
        {
          "valueReference": {
            "reference": "Patient/Patient1"
          }
        }
      ],
      "linkId": "questionnaire-item1",
      "type": "reference"
    }
  ],
  "status": "draft"
}
```
When I run publisher version 1.5.5, I encounter this error in my terminal
```org.hl7.fhir.exceptions.FHIRException: Type mismatch: the type Coding was expected, but org.hl7.fhir.r5.model.Reference was encountered at org.hl7.fhir.r5.model.Questionnaire$QuestionnaireItemInitialComponent.getValueCoding(Questionnaire.java:3407)```

The error can be reproduced by running the publisher with this [Example IG](https://github.com/reason-healthcare/ExampleIG)

**Comment by grahamegrieve** [comment]
fixed
