### ISSUE TITLE
BUG: The qa-eslintcompact.txt does not contain all the errors, warnings and informationals.

### ISSUE THREAD

**Issue by hvamstel** [HL7/fhir-ig-publisher#833]
pr #832 Should fix this.

The generation of the qa-eslintcompact.txt does not contain all the errors, warnings and informationals that are generated.
The ones that are called "linkerrors" were not present in the output.

We use this file to fill the problem window of visual code so that the user can just click on an error and is presented with the correct file and location automatically.

This completes this eslintcompact with that additional information so that it is complete and content wise identical to the other qa outputs. Now the total number of errors, warnings and informationals is correct with the summary given.

**Comment by lmckenzi** [comment]
Merged
