### ISSUE TITLE
Wrongly rendered HTML fragments in artifact's 'Detailed Descriptions' page

### ISSUE THREAD

**Issue by qligier** [HL7/fhir-ig-publisher#840]
In the 'Detailed Descriptions' page of artifacts, some HTML fragments are badly rendered:
![image](https://github.com/HL7/fhir-ig-publisher/assets/3299399/d53107dd-e06c-4762-a59d-df3253a8a749)

Example in CH-Core:
https://build.fhir.org/ig/hl7ch/ch-core/StructureDefinition-ch-core-epr-consent-definitions.html
The **Pattern Value** of `Consent.scope` and `Consent.policyRule` is badly rendered in the three tabs (differential, key and snapshot).
In the snapshot table, the same issue appears for the `Consent.identifier` **Example**.

From what I saw in the IG, it only impacts the **Pattern Value** and **Example** items rendering.

The IG was build with the IG Publisher v1.5.11.
https://build.fhir.org/ig/hl7ch/ch-core/branches/__default/build.log
https://github.com/hl7ch/ch-core

**Comment by grahamegrieve** [comment]
Fixed. see https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/New.20IG-Publisher/near/416688719

**Comment by qligier** [comment]
Thanks, it looks nice!
