### ISSUE TITLE
Link to ValueSet URL should default to the valueset.url not the terminology server that validated the ValueSet

### ISSUE THREAD

**Issue by mjosborne1** [HL7/fhir-ig-publisher#845]
Since FHIR IG Publisher Version 1.5.14 (Git# d19fffc41c80) the link to the ValueSet has been broken in the AU Base profiles. Instead of pointing at ValueSet url, the link points at the server which validated the ValueSet, in this case tx.ontoserver
So for example in AU Base, au-encounter.xml has this element binding:

 ``` <element id="Encounter.type">
      <path value="Encounter.type" />
      <binding>
        <strength value="preferred" />
        <valueSet value="https://healthterminologies.gov.au/fhir/ValueSet/encounter-type-1" />
      </binding>
    </element>
```

But the resulting html page **(StructureDefinition-au-encounter.html)** has this incorrect link href="https://tx.ontoserver.csiro.au/fhir/ValueSet/encounter-type-1":

```
Binding: </span><a href="https://tx.ontoserver.csiro.au/fhir/ValueSet/encounter-type-1"    title="https://healthterminologies.gov.au/fhir/ValueSet/encounter-type-1">Encounter Type <img src="[external.png](https://github.com/HL7/fhir-ig-publisher/issues/external.png)"/></a>
 
```
 
Please adjust igPublisher to link to the url in the binding, but validate against preferred validation server.

**Comment by grahamegrieve** [comment]
This won't be happening. If the ig publisher gets the value set directly from the server, as in this case, it's up to the server to advise where the correct link for the canonical URL is. I won't be second guessing, or simply using the canonical, since that's not reliable. If the server doesn't advise, then the IG publisher uses the server's address since this is a known good address. 

So up to the server, not a IG publisher issue.

**Comment by mjosborne1** [comment]
Thanks Grahame. I believe that you pointed CSIRO at this extension. "http://hl7.org/fhir/tools/StructureDefinition/web-source". 
"This extension is for canonical resources to indicate where a human readable web page describing the resource can be found, if it’s at a different location to the canonical URL itself. Todo: This might be considered for moving to the core extensions pack"

Some testing by both Michael Lawley and myself could not get this to work on the ValueSets we tested. A search of the igPublisher source code could not find any reference to web-source. 

Can you please confirm if the web-source tools extension has been implemented in fhir-ig-publisher yet?
