### ISSUE TITLE
Plantuml engine complains about hidden relationships in model source

### ISSUE THREAD

**Issue by thomiz** [HL7/fhir-ig-publisher#856]
This code is valid plantuml and runs fine on the plantuml testservers :
~~~plantuml
(soke) -down[hidden]- (lese)
(indeksere) -down[hidden]- (dele)
~~~

However, the integrated plantuml renderer in the ig-publisher complains, and outputs this error.
~~~
onGenerate.plantUml.ig:
     [java] Error line 16 in file: /github/workspace/VitalSigns/input/images-source/main-use-case.plantuml
     [java] Some diagram description contains errors
Publishing Content Failed: Java returned: 200
~~~

Plantuml code that don't contain hidden relationships runs fine with the ig-publisher.

**Comment by costateixeira** [comment]
the publisher uses the Apache or MIT release of PlantUML version 2023-6.
Did you try the code against that?

**Comment by thomiz** [comment]
Nope, always test my code on the latest release from plantuml servers 😄

**Comment by costateixeira** [comment]
can you please test and see if that is the issue ? If so, we can update plantuml to the latest version

**Comment by thomiz** [comment]
I did try to download [plantuml-1.2023.6.jar](https://github.com/plantuml/plantuml/releases/download/v1.2023.6/plantuml-1.2023.6.jar) and that also seems to work fine, locally, even with hidden connections.  

However I can not locate a build using the different licencing types. And I have noticed earlier that licence type can make a difference in the plantuml results.

**Comment by costateixeira** [comment]
if you don't mind checking: https://sourceforge.net/projects/plantuml/files/

The ones we use are ASL and MIT

**Comment by thomiz** [comment]
The 2023.6 version should be fine.

I finally got around to download the older versions from sourceforge, and both mit and asl versions of 2023.6 renders the diagram containing hidden correctly. A really old version (2022) don't understand the [hidden] relationship though.

**Comment by thomiz** [comment]
I will run it again, to be shure nothing weird is going on in my workflow. I was running a recent publisher (49 hours old at the time) and java version 21.

**Comment by thomiz** [comment]
No luck, still stops at the hidden relationships.

[The full workflow run](https://github.com/HL7Norway/no-domain/actions/runs/7920848417/job/21624808081)

**Comment by thomiz** [comment]
Not a bug in the ig-publisher after all.

It was our (HL7 Norway's) ig-template that used an outdated base template. Thanks to @costateixeira for tipping me off on that bug.
