### ISSUE TITLE
capabilityStatement with operations

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#858]
The new IG rendering of capability statements seems to not show operations unless the operation is in the capabilityStatement with capabilitystatement-expectation is used. is this extension really manditory?

**Comment by JohnMoehrke** [comment]
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/capabilityStatement.20with.20operations

**Comment by JohnMoehrke** [comment]
description also seems to be critical to appear on the bottom of the page...

**Comment by JohnMoehrke** [comment]
I think I was working on MHD. 
https://profiles.ihe.net/ITI/MHD/CapabilityStatement-IHE.MHD.DocumentSource.Generate.html#

That might be right now.

**Comment by JohnMoehrke** [comment]
Previous version didnt render 
 https://profiles.ihe.net/ITI/MHD/4.2.1/CapabilityStatement-IHE.MHD.DocumentRecipient.Generate.html

**Comment by vassilpeytchev** [comment]
Sounds like documentation still is missing, I will leave this open while I investigate.

**Comment by vassilpeytchev** [comment]
Documentation of resource-level operations is working (as soon as I added some to the above example)

![image](https://github.com/HL7/fhir-ig-publisher/assets/48733120/d5564bf7-d770-4f60-8d0a-a3e3938a7a89)

Closing this issue.

**Comment by vassilpeytchev** [comment]
This has been fixed in the next version (1.6.21) and possibly earlier.
