### ISSUE TITLE
Support for custom HTML inside resources

### ISSUE THREAD

**Issue by keithboone** [HL7/fhir-ig-publisher#86]
The current automatically generated text renderings of resources are adequate but not ideal.
I'd love it if the IG-Builder could include support for better HTML content in Resource.text.

A first step might be to allow for _text files (like _intro and _notes) which would be slurped into the div content inside resource.txt.  At least that way, if someone wants to hand craft content, they can. 

I'd love it even more if there was a two stage process to automate generation of the _text component, possibly through a custom XSLT transformation of the resource prior to insertion of text content.

If there was a way to support the custom XSLT transform through a template operation, (or maybe there already is), that seems like the right way to address it.

**Comment by grahamegrieve** [comment]
you can populate the narrative by hand if you want. if you do, the IG publisher leaves it in place.

you can also provide liquid templates by resource type

**Comment by keithboone** [comment]
Uhmm... OK, I get you can do it.  But including a great big honking div isn't IG editor friendly.

How would **I** do it.  Terse statements aren't really documentation about how to do this, and there's not much in terms of documentation on how to accomplish it via Liquid templates.  If you really want to close it, could you at least point me in a direction.

**Comment by grahamegrieve** [comment]
https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/Using.20liquid
