### ISSUE TITLE
Jurisdiction is missing in package.json

### ISSUE THREAD

**Issue by nriss** [HL7/fhir-ig-publisher#867]
Adding jurisdiction is useful for advanced search, which is possible thanks to the jurisdiction field in the package.json file.

![image](https://github.com/HL7/fhir-ig-publisher/assets/48218773/7077708b-ca55-433c-b244-97c605247d32)

### Working example

Link : http://hl7.org/fhir/us/davinci-dtr

```json
{
  "name": "hl7.fhir.us.davinci-dtr",
  "version": "1.0.0",
  "tools-version": 3,
  "type": "fhir.ig",
  "date": "20201223035410",
  "license": "CC0-1.0",
  "canonical": "http://hl7.org/fhir/us/davinci-dtr",
  "url": "http://hl7.org/fhir/us/davinci-dtr/STU1",
  "title": "Da Vinci - Documentation Templates and Rules",
  "description": "Guidelines for documentation templates and rules for coverage requirements (built Wed, Dec 23, 2020 03:54+0000+00:00)",
  "fhirVersions": [
    "4.0.1"
  ],
  "dependencies": {
    "hl7.fhir.r4.core": "4.0.1"
  },
  "author": "HL7 Clinical Decision Support Work Group",
  "directories": {
    "lib": "package",
    "example": "example"
  },
  "jurisdiction": "urn:iso:std:iso:3166#US"
}
```

# Problem

When we developed IGs from fsh & IG publisher, adding the jurisdiction on the sushi-config file only adds it as a flag in the IG and in the ImplementationGuide resource, but not in the package.json

### Example
Links : https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/blob/main/sushi-config.yaml, https://interop.esante.gouv.fr/ig/fhir/ror/

Jurisdiction in the sushi-config
![image](https://github.com/HL7/fhir-ig-publisher/assets/48218773/006f1a5e-b0ac-43ea-bcd3-9f5e25d40ad6)

Jurisdiction in the IG resource + flag : 
<img width="443" alt="image" src="https://github.com/HL7/fhir-ig-publisher/assets/48218773/3c0104ad-1b58-4a56-8593-6975b6758858">
![image](https://github.com/HL7/fhir-ig-publisher/assets/48218773/5772c053-d340-4393-b41a-09dd9af1fb9f)

But not in the package.json :  
```json
{
  "name" : "ans.fhir.fr.ror",
  "version" : "0.2.0",
  "tools-version" : 3,
  "type" : "IG",
  "date" : "20240112085110",
  "license" : "CC0-1.0",
  "canonical" : "https://interop.esante.gouv.fr/ig/fhir/ror",
  "url" : "https://interop.esante.gouv.fr/ig/fhir/ror/0.2.0",
  "title" : "Répertoire national de l’Offre et des Ressources en santé et accompagnement médico-social",
  "description" : "Ressources de conformité basées sur le modèle d'exposition 3.0 du ROR (built Fri, Jan 12, 2024 08:51+0000+00:00)",
  "fhirVersions" : ["4.0.1"],
  "dependencies" : {
    "hl7.fhir.r4.core" : "4.0.1",
    "hl7.terminology.r4" : "5.3.0",
    "hl7.fhir.uv.extensions.r4" : "1.0.0",
    "ans.annuaire.fhir.r4" : "0.2.0",
    "hl7.fhir.fr.core" : "1.1.0",
    "hl7.fhir.uv.bulkdata" : "2.0.0",
    "ans.fr.securisation-transport" : "1.2.0"
  },
  "author" : "ANS",
  "maintainers" : [
    {
      "name" : "ANS",
      "url" : "https://esante.gouv.fr"
    }
  ],
  "directories" : {
    "lib" : "package",
    "example" : "example"
  }
}
```
### Consequence

The advanced search for French jurisdiction is not available

This issue has been discussed with @M-Priour, @sdemeyANS and @wardweistra

**Comment by grahamegrieve** [comment]
wow. Fixed next release
