### ISSUE TITLE
Narrative rendering of CapabilityStatement.imports

### ISSUE THREAD

**Issue by bheale** [HL7/fhir-ig-publisher#873]
The CapabilityStatement.imports field (e.g. "imports" : [
:link: "http://hl7.org/fhir/us/core/CapabilityStatement/us-core-client"
]}
) is not referenced in the narrative produced by the IG Template when providing a requirements capability statement. Could the IG template populate a sentence, or something, with the URL(s) in the imports statement as part of the rendered narrative? Something like 'This capability statement imports from <list urls>. Please refer to the referenced capability statements for full information on the capabilities defined by this capability statement'

Right now, a casual reader will assume the CapabilityStatement is underspecified, rather than understand that the imports field means the capability statement actually comprises more. E.g. The IG wants to use the US Core capability statement as a base and add only a few additional must supports. One option is to copy the entire US Core capability statement and work from there. But the imports field is way more elegant for a requirements capability statement.

**Comment by bheale** [comment]
I think this is related to https://github.com/HL7/fhir-ig-publisher/issues/311 is related

**Comment by grahamegrieve** [comment]
not related to #311

**Comment by grahamegrieve** [comment]
fixed next release
