### ISSUE TITLE
path-binary parameter doesn't seem to work

### ISSUE THREAD

**Issue by costateixeira** [HL7/fhir-ig-publisher#876]
path-pages does what path-binary should do.

**Comment by grahamegrieve** [comment]
why? Looks ok to me

**Comment by costateixeira** [comment]
https://build.fhir.org/ig/DigitalSQR/smart-dak-tb/branches/path-binary/dictionary.html

**Comment by lmckenzi** [comment]
path-pages is being used with input/images and template/config, which are definitely intended to be "copy this folder across with no intervention" folders.  The question is whether that's what's happening or not.  None of the 'pages' folders are actually being identified by parameters (e.g. pagecontent, intro-notes).  More investigation is needed here about how these parameters are actually functioning.

**Comment by lmckenzi** [comment]
We will close this.  The names are misleading, but it's too late to fix them.
