### ISSUE TITLE
Add support for rendering of the FCP Approved Specification icon

### ISSUE THREAD

**Issue by reubendaniels** [HL7/fhir-ig-publisher#899]
If the IG’s ImplementationGuide resource includes the fcp-approved-specification Boolean parameter with a value of ‘true’ as follows:
 
```
<parameter>
    <code>
        <system value=http://hl7.org/fhir/tools/CodeSystem/ig-parameters/>
        <code value="fcp-approved-specification"/>
    </code>
    <value value="true"/>
</parameter>
```
 
then the IG Publisher will render the FCP Approved Specification icon

![HL7-FHIR-Community-Process-Approved-Specification-icon](https://github.com/HL7/fhir-ig-publisher/assets/685113/4c8b9ee2-8539-40b2-8b09-050d8259cf91)

in the top banner. The screenshot below demonstrates this:

<img width="1110" alt="image" src="https://github.com/HL7/fhir-ig-publisher/assets/685113/b0421db0-46f4-420a-95b8-6643c3b866c7">

**Comment by lmckenzi** [comment]
We only want this enabled when it's a non-HL7 published IG.  Should spit out a warning if it appears in anything derived from the HL7 international template.

Question: Should this be a registered trade mark (at least in the US)?  Also, no "(R)" is on the FHIR flame, and there should be.
Should this hyperlink to a registry?  to a website?  If so, where?

**Comment by ElliotSilver** [comment]
Is there a way we provide some level of assurance that only authorized IGs use this icon?

**Comment by lmckenzi** [comment]
Done
