### ISSUE TITLE
Can't find [content.attachment.url] in the bundle

### ISSUE THREAD

**Issue by adamzkover** [HL7/fhir-ig-publisher#906]
For the document Bundle at
https://github.com/felleskatalogen/sample-ig/blob/document-docref-url/input/resources/Bundle-Document-DocRef.xml
the following information message is generated:
`Can't find 'http://example.com/nowhere.txt' in the bundle (Bundle.entry[1].resource.content[0].attachment.url)`

It is my understanding that the URL is supposed to point to where the binary data is available on the internet, it is not meant to be something in the Bundle.

The same message is not generated when the Bundle type is collection:
https://github.com/felleskatalogen/sample-ig/blob/document-docref-url/input/resources/Bundle-DocRef.xml

Why is the message generated for the document Bundle?

**Comment by grahamegrieve** [comment]
to let you know that it's not in the Bundle, and you might want to put it there. Seems like a reasonable information message to me

**Comment by adamzkover** [comment]
Wouldn't that reasoning apply to the collection Bundle as well?

In case I wanted to put the data in the Bundle, do I have other options than a Binary with Base64 data inline? The real use case is MP4 files that are around 10-15 MB.

**Comment by grahamegrieve** [comment]
> Wouldn't that reasoning apply to the collection Bundle as well?

no. I mean, you could reason the same but the rules around documents relate to coherent content with everything that matters in the document. Hence, a note if it's somewhere else (there's no rule it has to be in the document unless it's attested content, and the validator can't know about that)

> In case I wanted to put the data in the Bundle, do I have other options than a Binary with Base64 data inline? The real use case is MP4 files that are around 10-15 MB.

no. it's going to be base64 one way or another if it's in the bundle

**Comment by adamzkover** [comment]
Thank you Grahame for the detailed explanation.
