### ISSUE TITLE
Rendering has a bug in subscriptions backport

### ISSUE THREAD

**Issue by jkiddo** [HL7/fhir-ig-publisher#909]
https://build.fhir.org/ig/HL7/fhir-subscription-backport-ig/Basic-r4-encounter-complete.html

<img width="1155" alt="image" src="https://github.com/HL7/fhir-ig-publisher/assets/211696/3a360069-5460-4bee-96fa-f7ac068ac09b">

**Comment by grahamegrieve** [comment]
fixed next release
