### ISSUE TITLE
QA messages error

### ISSUE THREAD

**Issue by alejosv** [HL7/fhir-ig-publisher#923]
After running `./_genonce.sh` and checking `qa.html` in the browser with a freshly initialized project, the errors section shows two errors:

|Path |Severity |Message|
|:-------|-------------|:-------------|
|StructureDefinition.text.div | error | Hyperlink 'StructureDefinition-MyPatient-definitions.html#rPatient' at 'div/table/tr/td/a' for 'Patient' does not resolve|
|StructureDefinition.text.div | error | Hyperlink 'StructureDefinition-MyPatient-definitions.html#rPatient.name' at 'div/table/tr/td/a' for 'name' does not resolve|

Previous versions of `_genonce.sh` notified these messages as warnings, even though they are not issues with the FSH files.

This is my environment:
```
$ node -v 
v18.17.1

$ npm -v 
10.8.1

$ java -version: 
openjdk version "11.0.23" 2024-04-16
OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1)
OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)

$ jekyll -v
jekyll 4.3.3

$ ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

$ sushi -v
SUSHI v3.11.0 (implements FHIR Shorthand specification v3.0.0-ballot)

FHIR IG Publisher Version 1.6.14 (Git# 8074c42c0755). Built 2024-07-04T03:47:02.626Z

```
Isn't it supposed to generate any errors?

**Comment by grahamegrieve** [comment]
what's a GitHub repository that demonstrates the error?

**Comment by alejosv** [comment]
Thanks @grahamegrieve I not sure if I understand que question, when you say "what's a GitHub repository that demonstrates the error?." you mean `fhir-ig-publisher` or `sushi` repository or my github project repository?

**Comment by grahamegrieve** [comment]
a GitHub repo of yours that runs on the ci-build and reproduces the problem

**Comment by alejosv** [comment]
Is the same errors to show here:

https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/qa.html#svi27
https://build.fhir.org/ig/Minsal-CL/SIGTEv2-IG/qa.html#svi28

**Comment by alejosv** [comment]
> @alejosv - is this now resolved?

Yes !!
