### ISSUE TITLE
unknown status qa-preview

### ISSUE THREAD

**Issue by nriss** [HL7/fhir-ig-publisher#924]
Hi!

I got this error message : Error: Exception in thread "main" java.lang.Error: unknown status qa-preview

https://github.com/ansforge/IG-fhir-annuaire/actions/runs/9872284187/job/27262072696

The status qa-preview exists in the publisher-release documentation & in the fsh documentation

The same status worked using v1.6.8 few days ago : https://github.com/ansforge/IG-fhir-repertoire-offre-ressources-sante/actions/runs/9187943127/job/25266672153

**Comment by grahamegrieve** [comment]
https://github.com/HL7/fhir-ig-publisher/commit/3384ef147513455db599a660083a01b34294b3b0 - it was changed to preview because qa-preview is not correct according to the templates

**Comment by nriss** [comment]
Okay! Thanks :)
