### ISSUE TITLE
CapabilityStatement with document

### ISSUE THREAD

**Issue by JohnMoehrke** [HL7/fhir-ig-publisher#927]
The CapabilityStatement.document elements are not displayed at all.

Recommend at least just display the mode, documentation, and profile as a bullet list.

**Comment by lmckenzi** [comment]
Agree that the rendering should cover this.  Should also show messaging.

**Comment by vassilpeytchev** [comment]
fhir-tests https://github.com/FHIR/fhir-test-cases/pull/187
org.hl7.fhir.core https://github.com/hapifhir/org.hl7.fhir.core/pull/1718

**Comment by JohnMoehrke** [comment]
seems this has been implemented
