### ISSUE TITLE
CapabilityStatement rendering of supported profiles should display the profile Title where possible

### ISSUE THREAD

**Issue by caspears** [HL7/fhir-ig-publisher#929]
In the rest summary table, the supported profiles use the title with a link to the profile (if the profile is defined in the IG).

However, in the rest resource detail section the Supported Profiles list only includes a list of urls that link to the url included, however, it should appear like the summary table and display the profile title that links to the profile (if the profile is defined in the IG). 

example:
![image](https://github.com/user-attachments/assets/32182cf5-6531-4f27-a7d5-66bd612aa848)

https://build.fhir.org/ig/HL7/carin-bb/CapabilityStatement-c4bb.html

This appears to be an issue with the resource.profile in addition to resource.supportedProfile

**Comment by caspears** [comment]
Example here: https://build.fhir.org/ig/HL7/carin-bb/CapabilityStatement-c4bb.html

**Comment by vassilpeytchev** [comment]
fhir-tests https://github.com/FHIR/fhir-test-cases/pull/187
org.hl7.fhir.core https://github.com/hapifhir/org.hl7.fhir.core/pull/1718

**Comment by JohnMoehrke** [comment]
close #927

**Comment by lmckenzi** [comment]
Complete
