### ISSUE TITLE
Package Publisher as Docker Container

### ISSUE THREAD

**Issue by chgl** [HL7/fhir-ig-publisher#93]
For easier integration into CI pipelines it would be great if the publisher were also released as a Docker container. Such a container will include the publisher.jar and all dependencies required to run it.

I'd definitely work on a PR for this if there's interest. Ideally, this container would be build and published for each release. Docker Hub provides an easy way to build containers from a given repo: https://docs.docker.com/docker-hub/builds/. Are there any existing HL7/FHIR Docker Hub repos which might house such a container image?

**Comment by lmckenzi** [comment]
Closing as handled by #97
