### ISSUE TITLE
Validating CodeSystems in UTG doesn't report duplicate workgroup extensions

### ISSUE THREAD

**Issue by brianpos** [HL7/fhir-ig-publisher#942]
Here are 2 examples of resources that should be producing warnings or errors
https://terminology.hl7.org/6.0.2/CodeSystem-v2-0350.json.html
https://terminology.hl7.org/6.0.2/CodeSystem-v2-0351.json.html

Discussion is here too:
https://chat.fhir.org/#narrow/stream/194616-terminology-.2F-utg/topic/New.20Warnings

These are related to the issue list that I've attached in here:
https://jira.hl7.org/browse/UP-592

**Comment by lmckenzi** [comment]
@brianpos This is actually an issue with the HAPI validator - it's not enforcing that the extension cardinality is being adhered to.  Please submit against HAPI and close this one (with a link)

**Comment by brianpos** [comment]
Thanks, will do.
