### ISSUE TITLE
Rendering of SearchParameter conformance expectations

### ISSUE THREAD

**Issue by dbojicic** [HL7/fhir-ig-publisher#962]
It would be helpful if the conformance expectations around comparators, modifiers, chains, targets etc were clearly rendered in the narrative for SearchParameters. 

AU Core, like US Core, extends the usage context of the [Conformance Expectation](https://hl7.org/fhir/extensions/StructureDefinition-capabilitystatement-expectation.html) extension to define these expectations (assuming this is a tooling 'hack' that allows this extension outside of CapabilityStatement use context) but the expectations are not included in generated narrative.

**Comment by lmckenzi** [comment]
Have raised as a HAPI issue - https://github.com/hapifhir/org.hl7.fhir.core/issues/1759
